### ISSUE TITLE
Unable to login externaly 

### ISSUE THREAD

**Issue by Qballjos** [tidusjar/Ombi#2339] opened 2018-06-19 17:40 UTC
#### Ombi build Version:

V 3.0.3407

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.2.5154

#### Operating System:

linuxserver/ombi docker image Linux 3.10.102 #15284

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-06-19 19:19:24.064 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:19:54.106 +02:00 [Information] 2 scheduled job(s) enqueued.
2018-06-19 19:20:24.120 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:20:54.142 +02:00 [Information] 2 scheduled job(s) enqueued.
2018-06-19 19:21:39.184 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:22:54.207 +02:00 [Information] 2 scheduled job(s) enqueued.
2018-06-19 19:25:39.227 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:26:09.237 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:27:54.249 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:30:39.266 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:31:24.276 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-06-19 19:33:24.295 +02:00 [Information] 1 scheduled job(s) enqueued.

```

#### Problem Description:

Unable to login to Ombi externaly, I use a synology docker installation with a reverse proxy to a subdomain with let's encrypt ssl. Never had any trouble before.

#### Reproduction Steps:

Go to my subdomain try to login, button doesn't respond site doesn't load.

**Comment by carnivorouz** [comment] 2018-06-19 17:43
Literally just dealt with this myself after one user complained.  Confirmed it with Tor and rolled back to 3.0.3383.

**Comment by Qballjos** [comment] 2018-06-19 17:47
Oke thnx for the update, I'll wait for a new version still works in my organizr homepage so don't need to roll back.

**Comment by tidusjar** [comment] 2018-06-19 18:14
@carnivorouz in future can you please report these things otherwise I will not know.

**Comment by Qballjos** [comment] 2018-06-19 18:32
@tidusjar Sure what is the server adres for ombi discord

**Comment by carnivorouz** [comment] 2018-06-19 19:05
> @carnivorouz in future can you please report these things otherwise I will not know.

@tidusjar Sure thing, and I am usually good about it.  This time I just finished resolving the issue myself when the notification for this ticket came through.

**Comment by tidusjar** [comment] 2018-06-20 06:21
Still not sure what @Qballjos issue is but it's not due to the recent release.

**Comment by carnivorouz** [comment] 2018-06-20 18:18
Not sure what the issue is either but I can definitely replicate it with the latest release.  Going back to .3383 allows me to login again.  On .3407 I'll get 'Incorrect username or password'.  It is behind nginx as well.

**Comment by Do-while-Bacon** [comment] 2018-06-25 16:35
I too had to roll back to 3383. I was not able to log in at all on 3407. The local login would say "incorrect username/password" and the Plex login button wouldn't do anything. I also noticed that the background picture was not loading. The Ombi logs did not pick up anything noteworthy.

I am running on CentOS 7.5 with Ngnix reverse proxy and using a base URL.

**Comment by tidusjar** [comment] 2018-06-25 16:38
I'm going to downgrade back to .net core 2.0 some point soon to see if that fixes the issue because the upgrade is the only thing that could have affected it.

**Comment by Do-while-Bacon** [comment] 2018-06-25 16:45
@tidusjar Happy to test anything you need. I can get on discord and screen share or whatever.

**Comment by carnivorouz** [comment] 2018-06-27 05:12
So, did some testing by copying nginx and ombi to a Fedora 28 system and I was able to login to the site externally.  This is good news but also complicates things for me on my side as I'll need to split up nginx now...fun

**Comment by tidusjar** [comment] 2018-06-27 07:59
Please can you check against the latest dev.

**Comment by carnivorouz** [comment] 2018-06-27 14:04
I get this error when I try to spin up 3.0.3438 on the Fedora 23 system that normally runs ombi:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=<some token here>'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Ombi.Store.Context.OmbiContext..ctor() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 18
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 48
Aborted
```
----------------------------------------------

**Comment by Do-while-Bacon** [comment] 2018-06-28 02:32
3.0.3441 is working normally for me again. Cheers.

**Closed** 2018-06-28 12:37 UTC
Labels: .net core

**Comment by anujpuri85** [comment] 2019-04-12 20:40
Having this issue now as well with the recent version (the previous version I had before I just updated was one from quite a long time ago). Was there an easy fix to this? I'm also behind nginx and not able to click the login button.

**Comment by tidusjar** [comment] 2019-04-12 20:51
What's in your logs

**Comment by anujpuri85** [comment] 2019-04-12 21:04
I don't see anything in the logs when trying to login. the only items I see in the logs are when I startup Ombi, at which point this displsy (again, seems to have to do with plex, but I don't even use plex - I use emby):

`2019-04-12 15:16:27.919 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.External.PlexController.GetFriends() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 256
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24`
