### ISSUE TITLE
PlexRequests service crashing every few hours

### ISSUE THREAD

**Issue by rfrowe** [tidusjar/Ombi#760] opened 2016-12-10 01:13 UTC
#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Ubuntu 16.04.1 LTS

#### Mono Version:
```
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 21 12:08:40 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen
```

#### Applicable Logs (from `/logs/` directory or the Admin page):
Output from `journalctl -u plexrequest.service`
```
Dec 05 23:25:54 Riker mono[32807]: Starting Up! Please wait, this can usually take a few seconds.
Dec 05 23:25:54 Riker mono[32807]: Version: 1.9.7
Dec 05 23:25:54 Riker mono[32807]: Location of the database: /opt/plexrequests.net/PlexRequests.sqlite
Dec 05 23:25:59 Riker mono[32807]: no configuration section <common/logging> found - suppressing logging output
Dec 05 23:25:59 Riker mono[32807]: Plex Requests is running on the following: http://+:3579/
Dec 05 23:25:59 Riker mono[32807]: All setup, Plex Requests is now ready!
Dec 06 20:06:59 Riker mono[32807]: [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List`1' threw an e
Dec 06 20:06:59 Riker mono[32807]:    --- End of inner exception stack trace ---
Dec 06 20:06:59 Riker mono[32807]:   at System.Threading.Timer+Scheduler.SchedulerThread () [0x0000f] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 06 20:06:59 Riker mono[32807]:   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 06 20:06:59 Riker mono[32807]:   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callb
Dec 06 20:06:59 Riker mono[32807]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, Sys
Dec 06 20:06:59 Riker mono[32807]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, Sys
Dec 06 20:06:59 Riker mono[32807]:   at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 06 20:06:59 Riker systemd[1]: plexrequests.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 20:06:59 Riker systemd[1]: plexrequests.service: Unit entered failed state.
Dec 06 20:06:59 Riker systemd[1]: plexrequests.service: Failed with result 'exit-code'.
```

#### Reproduction Steps:
1. Start plexrequests process as service
2. Wait.

**Comment by tidusjar** [comment] 2016-12-10 08:03
Version of mono?

**Comment by rfrowe** [comment] 2016-12-10 08:28
I put the output of `mono --version` in my original post. `4.6.2`?

**Comment by tidusjar** [comment] 2016-12-10 10:26
Oh yeah sorry!

So does it crash straight away?

**Comment by rfrowe** [comment] 2016-12-10 10:31
Here's the latest crash 
```
Dec 09 16:59:14 Riker mono[984]: Starting Up! Please wait, this can usually take a few seconds.
Dec 09 16:59:14 Riker mono[984]: Version: 1.9.7
Dec 09 16:59:14 Riker mono[984]: Location of the database: /opt/plexrequests.net/PlexRequests.sqlite
Dec 09 16:59:18 Riker mono[984]: no configuration section <common/logging> found - suppressing logging output
Dec 09 16:59:19 Riker mono[984]: Plex Requests is running on the following: http://+:3579/
Dec 09 16:59:19 Riker mono[984]: All setup, Plex Requests is now ready!
Dec 10 02:02:42 Riker mono[984]: [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'S
Dec 10 02:02:42 Riker mono[984]:    --- End of inner exception stack trace ---
Dec 10 02:02:42 Riker mono[984]:   at System.Threading.Timer+Scheduler.SchedulerThread () [0x0000f] in <8f2c484307284b51944a1a13a14
Dec 10 02:02:42 Riker mono[984]:   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <8f2c484
Dec 10 02:02:42 Riker mono[984]:   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionCon
Dec 10 02:02:42 Riker mono[984]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, Sy
Dec 10 02:02:42 Riker mono[984]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, Sy
Dec 10 02:02:42 Riker mono[984]:   at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:
Dec 10 02:02:43 Riker systemd[1]: plexrequests.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 02:02:43 Riker systemd[1]: plexrequests.service: Unit entered failed state.
Dec 10 02:02:43 Riker systemd[1]: plexrequests.service: Failed with result 'exit-code'.
```

As you can see by the timestamps it crashed after it was up for around 9 hours.

I haven't tried leaving it up for an extended period of time just run from a shell

**Comment by tidusjar** [comment] 2016-12-10 14:33
Hmmmm that's interesting. Is there anything in the Plex Requests logs?

**Comment by rfrowe** [comment] 2016-12-10 20:17
There's no such file as `/opt/plexrequests.net/logs/2016-12-10.log` for some reason. The latest I have is the 9th and there's nothing in there. I'll start it up again and see if it generates something useful. What should I set the log level to?

**Comment by tidusjar** [comment] 2016-12-10 21:05
Debug should be fine, what is it set to currently?

**Comment by rfrowe** [comment] 2016-12-10 21:11
It was set to error

**Comment by rfrowe** [comment] 2016-12-11 08:13
Alright, it just crashed again in debug mode. Here's `journalctl -u plexrequests.service`

```
Dec 10 13:08:00 Riker systemd[1]: Stopped Systemd script to run PlexRequests as a service.
Dec 10 13:08:00 Riker systemd[1]: Started Systemd script to run PlexRequests as a service.
Dec 10 13:08:02 Riker mono[35037]: Starting Up! Please wait, this can usually take a few seconds.
Dec 10 13:08:02 Riker mono[35037]: Version: 1.9.7
Dec 10 13:08:02 Riker mono[35037]: Location of the database: /opt/plexrequests.net/PlexRequests.sqlite
Dec 10 13:08:07 Riker mono[35037]: no configuration section <common/logging> found - suppressing logging output
Dec 10 13:08:07 Riker mono[35037]: Plex Requests is running on the following: http://+:3579/
Dec 10 13:08:07 Riker mono[35037]: All setup, Plex Requests is now ready!
Dec 10 22:44:57 Riker mono[35037]: [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List`1' threw an ex
Dec 10 22:44:57 Riker mono[35037]:    --- End of inner exception stack trace ---
Dec 10 22:44:57 Riker mono[35037]:   at System.Threading.Timer+Scheduler.SchedulerThread () [0x0000f] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 10 22:44:57 Riker mono[35037]:   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 10 22:44:57 Riker mono[35037]:   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callba
Dec 10 22:44:57 Riker mono[35037]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, Syst
Dec 10 22:44:57 Riker mono[35037]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, Syst
Dec 10 22:44:57 Riker mono[35037]:   at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 10 22:44:57 Riker systemd[1]: plexrequests.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 22:44:57 Riker systemd[1]: plexrequests.service: Unit entered failed state.
Dec 10 22:44:57 Riker systemd[1]: plexrequests.service: Failed with result 'exit-code'.
```

Here's the entire `2016-12-10.log`
```
2016/12/10 15:08:10.474 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: There are no requests to check.
2016/12/10 17:08:10.035 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: There are no requests to check.
2016/12/10 19:08:10.249 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: There are no requests to check.
2016/12/10 21:08:11.124 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: There are no requests to check.
```

**Comment by noahruss** [comment] 2016-12-11 18:27
Thus happens to me too, for now I've setup a crown job to restart the service every so often

**Comment by animosity22** [comment] 2016-12-12 12:20
I'm on mono v4.6.2 and notice the same thing. Nothing appears in the logs other than noted above. I'll have to turn mine up to debug as well.

**Comment by tidusjar** [comment] 2016-12-12 12:25
Can we potentially run mono in debug mode ? e.g. `mono --debug PlexRequests.exe` and then post the output. 

In the above errors there is nothing indicating anything inside my code is erroring, it looks like a mono bug but I need the debug logs to confirm to report to the mono team.

**Comment by gen3ric** [comment] 2016-12-12 16:18
Just want to note that I'm also experiencing this. On `Mono 4.6.2`, PlexRequests version 1.9.7. Mine becomes unresponsive and the CPU gets pegged. It's the only thing that will cause my 2xE5-2680v2  server to actually spool up the fans and I can hear it from throughout the house as soon as PR becomes unresponsive.  :laughing: 

My log from `/opt/plexrequests.net/logs/2016-12-08.log` is very brief:
```
2016/12/08 00:05:36.280 PlexRequests.Services.Jobs.RecentlyAdded Error: System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.OrderedEnumerable`2[TElement,TKey]..ctor (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IComparer`1[T] comparer, System.Boolean descending) [0x00016] in <63992662b765477a898ef49c$
  at System.Linq.Enumerable.OrderByDescending[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <63992662b765477a898ef49cdcc99ee2>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.GenerateMovieHtml (PlexRequests.Api.Models.Plex.RecentlyAddedModel movies, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x0001e] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x000bc] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Execute (Quartz.IJobExecutionContext context) [0x00016] in <cdbfe32bf01544fbb7d92659b1574a2a>:0  System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.OrderedEnumerable`2[TElement,TKey]..ctor (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IComparer`1[T] comparer, System.Boolean descending) [0x00016] in <63992662b765477a898ef49c$
  at System.Linq.Enumerable.OrderByDescending[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <63992662b765477a898ef49cdcc99ee2>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.GenerateMovieHtml (PlexRequests.Api.Models.Plex.RecentlyAddedModel movies, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x0001e] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x000bc] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Execute (Quartz.IJobExecutionContext context) [0x00016] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
2016/12/08 12:05:36.254 PlexRequests.Services.Jobs.RecentlyAdded Error: System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.OrderedEnumerable`2[TElement,TKey]..ctor (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IComparer`1[T] comparer, System.Boolean descending) [0x00016] in <63992662b765477a898ef49c$
  at System.Linq.Enumerable.OrderByDescending[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <63992662b765477a898ef49cdcc99ee2>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.GenerateMovieHtml (PlexRequests.Api.Models.Plex.RecentlyAddedModel movies, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x0001e] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x000bc] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Execute (Quartz.IJobExecutionContext context) [0x00016] in <cdbfe32bf01544fbb7d92659b1574a2a>:0  System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.OrderedEnumerable`2[TElement,TKey]..ctor (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IComparer`1[T] comparer, System.Boolean descending) [0x00016] in <63992662b765477a898ef49c$
  at System.Linq.Enumerable.OrderByDescending[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <63992662b765477a898ef49cdcc99ee2>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.GenerateMovieHtml (PlexRequests.Api.Models.Plex.RecentlyAddedModel movies, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x0001e] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x000bc] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
  at PlexRequests.Services.Jobs.RecentlyAdded.Execute (Quartz.IJobExecutionContext context) [0x00016] in <cdbfe32bf01544fbb7d92659b1574a2a>:0
```

**Comment by tidusjar** [comment] 2016-12-12 16:24
@gen3ric The errors that you have posted have been fixed in the next release.

**Comment by gen3ric** [comment] 2016-12-12 16:30
Gotcha, I will check that out when it comes down the pipe. Thanks.

**Comment by SuperPotatoMen** [comment] 2016-12-12 20:22
@gen3ric, but that is not the main problem

Can you do the same what tidusjar ask before? quote:
> Can we potentially run mono in debug mode ? e.g. mono --debug PlexRequests.exe and then post the output.
> 
> In the above errors there is nothing indicating anything inside my code is erroring, it looks like a mono bug but I need the debug logs to confirm to report to the mono team.

**Comment by rfrowe** [comment] 2016-12-12 22:01
I can do this later today

**Comment by animosity22** [comment] 2016-12-12 23:55
Sorry. My issue was completely unrelated and due to a DNS miconfiguration on my Linux box. Apologies as it does not seem related to anything else.

**Comment by rfrowe** [comment] 2016-12-13 00:55
Alright, systemd shows 
```
   CGroup: /system.slice/plexrequests.service
           └─40164 /usr/bin/mono --debug /opt/plexrequests.net/PlexRequests.exe
```
I'll paste the logs the next time it crashes

**Comment by rfrowe** [comment] 2016-12-14 00:50
Here's the output. I am certain that mono was run with the debug flag, however it doesn't look like it did much

```
Dec 12 16:54:19 Riker systemd[1]: Started Systemd script to run PlexRequests as a service.
Dec 12 16:54:19 Riker mono[40164]: Starting Up! Please wait, this can usually take a few seconds.
Dec 12 16:54:19 Riker mono[40164]: Version: 1.9.7
Dec 12 16:54:19 Riker mono[40164]: Location of the database: /opt/plexrequests.net/PlexRequests.sqlite
Dec 12 16:54:22 Riker mono[40164]: no configuration section <common/logging> found - suppressing logging output
Dec 12 16:54:22 Riker mono[40164]: Plex Requests is running on the following: http://+:3579/
Dec 12 16:54:22 Riker mono[40164]: All setup, Plex Requests is now ready!
Dec 13 02:06:15 Riker mono[40164]: [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List`1' threw an exception. ---> System.Threading.ThreadAbortException
Dec 13 02:06:15 Riker mono[40164]:    --- End of inner exception stack trace ---
Dec 13 02:06:15 Riker mono[40164]:   at System.Threading.Timer+Scheduler.SchedulerThread () [0x0000f] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 13 02:06:15 Riker mono[40164]:   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 13 02:06:15 Riker mono[40164]:   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 13 02:06:15 Riker mono[40164]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 13 02:06:15 Riker mono[40164]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 13 02:06:15 Riker mono[40164]:   at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 13 02:06:15 Riker systemd[1]: plexrequests.service: Main process exited, code=exited, status=1/FAILURE
Dec 13 02:06:15 Riker systemd[1]: plexrequests.service: Unit entered failed state.
Dec 13 02:06:15 Riker systemd[1]: plexrequests.service: Failed with result 'exit-code'.
```

**Comment by rfrowe** [comment] 2016-12-16 07:08
😢

**Comment by aktavor69** [comment] 2016-12-16 18:39
i have the same issue

**Comment by SuperPotatoMen** [comment] 2016-12-16 22:25
I found 2 open bug reports already on this issue:

https://bugzilla.xamarin.com/show_bug.cgi?id=49274 and: https://bugzilla.xamarin.com/show_bug.cgi?id=43320

Maybe @tidusjar can join the two bug reports on mono reporting platform

**Comment by SuperPotatoMen** [comment] 2016-12-16 22:40
there are working already on a fix:

https://github.com/mono/mono/pull/4156

**Comment by bjonness406** [comment] 2016-12-17 00:00
Dunno if this helps since this looks like a mono problem, but I am adding it here anyway.
Problem only started after 1.10.0 update for me.

Running plexrequest in a docker.
It crashes very random for me, and I get this error in the docker log

`[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List'1' threw an exception. ---> System.Threading.ThreadAbortException:
End of inner exception stack trace ---
at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x41aa7ed0 + 0x00098> in <filename unknown>:0
at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x41aa5130 + 0x0021a> in <filename unknown>:0
at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x41aa50f0 + 0x00028> in <filename unknown>:0
at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x41aa5020 + 0x00061> in <filename unknown>:0
at System.Threading.ThreadHelper.ThreadStart () <0x41aa4f80 + 0x00039> in <filename unknown>:0`

**Comment by overdox** [comment] 2016-12-20 07:57
Getting alot of errors generated like in the log below.
I have tried to run it both on a ubuntu server, and debian server with fresh install of mono and plexrequests.

Plex requests becomes unresponsive after about 20-30 minutes of uptime. The service is still running, I just can't access it.


2016/12/20 08:41:16.819 PlexRequests.Api.PlexApi Error: Exception when calling GetEpisodeMetaData for Plex, Retrying 00:00:02 PlexRequests.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x402e6e60 + 0x00197> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () <0x402de9a0 + 0x0005a> in <filename unknown>:0 
  at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x402de5d0 + 0x00043> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at PlexRequests.Api.ApiRequest.ExecuteXml[T] (IRestRequest request, System.Uri baseUri) <0x4031e3a0 + 0x00183> in <filename unknown>:0 
  at PlexRequests.Api.PlexApi+<>c__DisplayClass20_0.<GetEpisodeMetaData>b__0 () <0x409e7680 + 0x0002d> in <filename unknown>:0 
  at Polly.Policy+<>c__DisplayClass8_0`1[TResult].<Execute>b__0 () <0x402b2780 + 0x0001e> in <filename unknown>:0 
  at Polly.RetrySyntax+<>c__DisplayClass14_0.<WaitAndRetry>b__1 () <0x402b2610 + 0x0001a> in <filename unknown>:0 
  at (wrapper delegate-invoke) System.Func`1[Polly.Utilities.EmptyStruct]:invoke_TResult ()
  at Polly.Retry.RetryEngine.Implementation[TResult] (System.Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, System.Func`1 policyStateFactory) <0x402b19c0 + 0x000ac> in <filename unknown>:0

**Comment by tidusjar** [comment] 2016-12-20 07:59
@overdox Try and turn off episode searching, looks like the library might be a bit too big as Plex cannot serve our requests.

**Comment by overdox** [comment] 2016-12-20 08:11
@tidusja you might be right about that, currently sitting on 17340 episodes. Will try turning off the episode searching and see how it goes. Thanks for the tip.

**Comment by rfrowe** [comment] 2016-12-27 05:57
@overdox use triple backticks for code blocks next time :) 

So we just have to wait for the change to get propagated?

**Comment by tidusjar** [comment] 2016-12-27 09:45
@rfrowe there currently is no fix for the issue that @overdox posted. His episode library is too large and we are trying to get the information from Plex but it cannot serve all of our requests fast enough. I need to look into another way of doing it.

**Comment by rfrowe** [comment] 2016-12-28 03:56
I meant the original issue, which I'm not sure if that's related to @overdox's or not.

**Comment by ryanjoachim** [comment] 2017-01-03 03:24
Just wanted to pop in and say I ran into a very similar crashing issue, which was resolved by turning off episode searching.

I'm sitting on 2345 episodes currently. If you want logs, I can turn it back on and see what happens.

**Comment by CodaAmok** [comment] 2017-01-20 20:41
Me too on this issue

**Comment by hossame** [comment] 2017-01-22 05:35
+1 Seeing this issue as well

**Comment by tidusjar** [comment] 2017-01-23 13:35
Guys, the issue with saying 'me too' is that the cause of the issue could be completly different and it's difficult to say. if you are having an issue please raise a new Issue.

**Comment by SuperPotatoMen** [comment] 2017-03-26 10:42
won't fix for now. @tidusjar is going to re-write it to .net port but that will take a LOT of time.
I will close this for now.

https://github.com/tidusjar/Ombi/issues/865

**Closed by SuperPotatoMen** 2017-03-26 10:42 UTC
Labels: External problem, Stable branch
