### ISSUE TITLE
Updating, getting-  Value cannot be null. Parameter name: path1

### ISSUE THREAD

**Issue by KevinFromUpThere** [tidusjar/Ombi#2907] opened 2019-03-28 19:16 UTC
When executing ombi.updater.exe I get:
 Value cannot be null.
Parameter name: path1

**To Reproduce**
1Execute ombi.updater.exe in administrator mode.

**Expected behavior**
Updated succesfully!

**Screenshots**
C:\Users\Kevin\Downloads\OMBI.windows-32bit\updater>ombi.updater.exe
 =======================================
        Starting the Ombi Updater
 =======================================
[7296]: Killing process
[7296]: Waiting for exit
[7296]: Process terminated successfully

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Ombi.Updater.Installer.StartOmbi(StartupOptions options) in C:\projects\requestplex\src\Ombi.Updater\Installer.cs:line 86
   at Ombi.Updater.Installer.Start(StartupOptions opt) in C:\projects\requestplex\src\Ombi.Updater\Installer.cs:line 48
   at Ombi.Updater.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi.Updater\Program.cs:line 23

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment] 2019-03-29 09:14
Duplicate of #1460

**Closed by tidusjar** 2019-03-29 09:14 UTC
