### ISSUE TITLE
Ombi V4 - Specific TV Series item unable to load/request

### ISSUE THREAD

**Issue by Reddax** [tidusjar/Ombi#3717] opened 2020-08-09 21:43 UTC
**Describe the bug**
I've found a TV series that when searching and clicking on, I just get an infinite loading screen and so unable to request. This happens on my server and also on the test link (https://app.ombi.io/)

**To Reproduce**
1. Go to Discovery
2. Search "Band Of Gold'
3. Click the top link

**Expected behavior**
You should be able to click on the item "Band of Gold" and should load up the details and allow you to request.

**Screenshots**
![20200809_152824 (Small)](https://user-images.githubusercontent.com/1349626/89742444-f1cbcd80-da91-11ea-89a4-d30b2d3b6825.jpg)

**Logs (Logs directory where Ombi is located)**
Don't have logs but easily replicable

**Desktop (please complete the following information):**
 - OS: Windows desktop & Android browser

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
4.0.442.0
- Media Server [e.g. Plex]
Plex

**Additional context**

**Comment by bagobones** [comment] 2020-08-16 04:06
My users report the same for many requests, might have to roll back to v3.

Example searching for "TOTS" or "T.O.T.S." and then selecting the search result seems to hang TV or Combined search.

**Comment by douglasparker** [comment] 2020-08-18 03:19
> Example searching for "TOTS" or "T.O.T.S." and then selecting the search result seems to hang TV or Combined search.

I can reproduce this issue when clicking on the `Band of Gold` and `T.O.T.S.` search results.

**Comment by dcbinder** [comment] 2020-09-23 04:42
The same issue here when searching for the TV Show "Eating History". Thanks in advance.

**Comment by dpiper01** [comment] 2020-10-17 17:35
> The same issue here when searching for the TV Show "Eating History". Thanks in advance.

Also have the same issue for eating history

**Comment by Reddax** [comment] 2020-11-11 09:18
Could this issue be prioritized? It's happening for a fair few shows. it does it for 'Seduced: Inside' too. Stops users and myself for requesting shows.

**Comment by bernarden** [comment] 2020-11-24 08:00
After debugging the issue for 'Band of Gold' I found out that the TVDB ID stored in themoviedb.org is incorrect.
Currently themoviedb.org stores 85115 instead of 71552, and as a result the request `http://api.tvmaze.com/lookup/shows?thetvdb=85115` returns 404. Currently this 404 is not explicitly handled, so Ombi API returns an empty response (204) to the client side. The client side expects to find an id on the response and when it doesn't it throws an exception.

Links:
https://www.thetvdb.com/series/band-of-gold
https://www.themoviedb.org/tv/9091-band-of-gold/edit?active_nav_item=external_ids

**Comment by bernarden** [comment] 2020-11-24 08:47
For 'Seduced: Inside the NXIVM Cult' trakt.tv stores incorrect IMDB id (tt13282962 instead of tt13269706), so when Ombi's request `https://api.trakt.tv/shows/tt13269706?extended=full` we get 404. I will create a PR to ignore the 404 since all the information returned from tract.tv is optional.

**Comment by bernarden** [comment] 2020-11-24 09:22
Request `http://api.tvmaze.com/lookup/shows?thetvdb=377698` to load information about "Eating History" tv shows fails because tvmaze.com is missing Thetvdb id.

Link: https://www.tvmaze.com/showexternal/view?id=46089

**Comment by bernarden** [comment] 2020-11-24 09:30
"T.O.T.S" request `http://api.tvmaze.com/lookup/shows?thetvdb=363930` is failing (404) because tvmaze.com has incorrect Thetvdb id (364268 instead of 363930).

Links:
https://www.tvmaze.com/showexternal/view?id=36030
https://thetvdb.com/series/t-o-t-s

**Comment by kfulgham** [comment] 2020-12-20 04:36
I have the same problem, but expanded. Any movie or tv show gets the spinning wheel of loading.

**Comment by bruvv** [comment] 2020-12-30 14:04
Looks like the same issue:
https://github.com/tidusjar/Ombi/issues/3861
https://github.com/tidusjar/Ombi/issues/3947

**Comment by tidusjar** [comment] 2021-01-18 09:31
This should be resolved with the latest version

**Closed by tidusjar** 2021-01-18 09:31 UTC
Labels: Needs investigation

**Comment by JDIacobbo** [comment] 2021-06-04 18:08
I believe I am also having this issue. Just recently updated to 4.0.1403 when this issue began. Was working on the previous version (4.0.790 I think). When I attempt to view a TV Show request I get the infininte spinning circle and the following error in the logs. Movies do not have any issue.

[Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/361566?api_key=[censored]&language=en&append_to_response=videos,credits,similar,recommendations,external_ids,keywords,images

**Comment by tidusjar** [comment] 2021-06-04 18:10
What TV show?

**Comment by JDIacobbo** [comment] 2021-06-04 18:11
Any show will cause this, but specifically I'm trying to load Dickinson and Mare of Easttown.

**Comment by JDIacobbo** [comment] 2021-06-05 17:14
This seems to have fixed itself. Not sure what changed but thanks anyway!

**Comment by MaleNurse** [comment] 2021-07-23 18:43
Occurs for me with "The Problem with Jon Stewart". TVDB and TMDB have different IDs ([400756](https://www.thetvdb.com/series/the-problem-with-jon-stewart) and [123149](https://www.themoviedb.org/tv/123149-the-problem-with-jon-stewart), respectively).

```
2021-07-23 11:24:16.629 -07:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/400756?api_key=[redacted]&language=en&append_to_response=videos,credits,similar,recommendations,external_ids,keywords,images

2021-07-23 11:34:27.387 -07:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
2021-07-23 11:34:27.387 -07:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model)
```

**Comment by craigg75** [comment] 2021-08-01 19:01
Exact same thing happening to me. This has been a bug for almost a year yet no indication that they are trying to fix it. It renders this app pretty useless. Bummer :(

**Comment by tidusjar** [comment] 2021-08-01 19:55
I don’t actively monitor closed issues. 

Please can you raise a new issue with the appropriate details and I’ll take a look!
