### ISSUE TITLE
TV Show Notification via discord has half empty notifications

### ISSUE THREAD

**Issue by hagabla** [tidusjar/Ombi#2338] opened 2018-06-18 21:48 UTC
#### Ombi build Version:

3.0.3407

#### Update Branch:

stable

#### Operating System:

Debian 8

#### Problem Description:

discord notification on tv show request filled looks like this:
https://imgur.com/a/ZDdaUWb
Works fine with movies

**Comment by tidusjar** [comment] 2018-06-27 07:48
Cannot reproduce, seems to be working fine for me

**Comment by hagabla** [comment] 2018-06-27 18:18
Weird, I can reproduce it 100% of the time. On discord another guy mentioned the same yesterday.

**Comment by tidusjar** [comment] 2018-06-27 20:35
Any specific TV shows? What's the template set as in the settings?

**Comment by hagabla** [comment] 2018-06-27 20:37
Every TV Show

template is the default one.

Hello! You   {Title} on {ApplicationName}! This is now available! :)

**Comment by tidusjar** [comment] 2018-06-27 21:06
Does it happen when you manually mark something as available or only when Ombi automatically marks it?

**Comment by hagabla** [comment] 2018-06-27 21:33
automatically, never tried manually

**Comment by tidusjar** [comment] 2018-06-28 12:41
Can you try manually for me?

**Comment by tidusjar** [comment] 2018-06-28 12:53
Found it, Fixed in develop

**Closed by tidusjar** 2018-06-28 12:53 UTC
Labels: Cannot reproduce, bug / issue
