### ISSUE TITLE
Stuck "Loading..." on mobile browsers

### ISSUE THREAD

**Issue by spencercharest** [tidusjar/Ombi#1724] opened 2017-11-19 21:13 UTC
#### Ombi build Version:

V 3.0.2363

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.9.7.4441 

#### Operating System:
Docker on Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
Ombi gets stuck on loading screen 

#### Reproduction Steps:
Open latest Ombi on mobile Chrome or Safari.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment] 2017-11-19 21:39
Can you include some browser logs. 

What did you do for this to happen? Did you change anything?

**Comment by spencercharest** [comment] 2017-11-20 01:03
[log-20171119.txt](https://github.com/tidusjar/Ombi/files/1486172/log-20171119.txt)

Here is the log from today. The latest update seems to have caused this. Everything works fine on browsers on OS X (Chrome, Safari, Firefox tested). The issue is only on iOS mobile browsers (Chrome and Safari).

**Comment by maxlesser** [comment] 2017-11-22 16:51
I am also seeing this issue, but for all browsers. I'm going through the process of setting up Ombi for the first time via nginx reverse proxy - Ombi launches fine, and is accessible via nginx, but all I get is a screen that says "Loading..." forever. 

Nothing shows in logs or the terminal where I launched Ombi when I load the page - Logs just show server starting up/stopping when I manually stop it: 

> 2017-11-22 10:53:36.357 -05:00 [Information] Hangfire Server stopped.
> 2017-11-22 11:02:09.823 -05:00 [Information] Start installing Hangfire SQL objects...
> 2017-11-22 11:02:10.122 -05:00 [Information] Hangfire SQL objects installed.
> 2017-11-22 11:02:10.141 -05:00 [Information] Starting Hangfire Server
> 2017-11-22 11:02:10.144 -05:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
> 2017-11-22 11:02:10.144 -05:00 [Information] Using the following options for Hangfire Server:
> 2017-11-22 11:02:10.144 -05:00 [Information]     Worker count: 1
> 2017-11-22 11:02:10.144 -05:00 [Information]     Listening queues: 'default'
> 2017-11-22 11:02:10.144 -05:00 [Information]     Shutdown timeout: 1.00:00:00
> 2017-11-22 11:02:10.144 -05:00 [Information]     Schedule polling interval: 00:00:15
> 2017-11-22 11:09:24.758 -05:00 [Information] Hangfire Server stopped.
> 2017-11-22 11:15:28.431 -05:00 [Information] Start installing Hangfire SQL objects...
> 2017-11-22 11:15:28.474 -05:00 [Information] Hangfire SQL objects installed.
> 2017-11-22 11:15:28.494 -05:00 [Information] Starting Hangfire Server
> 2017-11-22 11:15:28.497 -05:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
> 2017-11-22 11:15:28.497 -05:00 [Information] Using the following options for Hangfire Server:
> 2017-11-22 11:15:28.497 -05:00 [Information]     Worker count: 1
> 2017-11-22 11:15:28.497 -05:00 [Information]     Listening queues: 'default'
> 2017-11-22 11:15:28.497 -05:00 [Information]     Shutdown timeout: 1.00:00:00
> 2017-11-22 11:15:28.497 -05:00 [Information]     Schedule polling interval: 00:00:15
> 2017-11-22 11:22:19.185 -05:00 [Information] Hangfire Server stopped.

Is there a requirement to access the site and do some setup without the reverse proxy before it will work via reverse proxy?

**Comment by spencercharest** [comment] 2017-11-22 16:54
I'm also using a NGINX reverse proxy.

**Comment by maxlesser** [comment] 2017-11-22 17:13
Here is my nxinx reverse proxy location block:

`location /ombi {
                auth_request /auth-admin;
                proxy_pass http://127.0.0.1:5000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection keep-alive;
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                add_header X-Frame-Options "SAMEORIGIN";
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
`

**Comment by VossenTech** [comment] 2017-11-26 01:48
I'm not sure how to get logs from an ios browser but I did some testing and can add that this is not a reverse proxy issue, I too run one but I get the same response when trying to hit the internal address. I also spun up a brand new instance and it has this issue out of the box, so it is not a configuration issue. I am running on windows so it also appears it doesn't matter which OS you are hosting on.

**Comment by zin105** [comment] 2017-11-26 18:01
This is what I get in my browser log. ******** = my domain

`********/:1 Refused to execute script from 'https://********/dist/vendor.js?v=kjSoEE_pVMzibhxQVuBd4J_AYuFf4T8SWjKSDD3gLe4' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
********/:64 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://********/loading.css?v=k33zb3c0-ToEQSx13OJIBKNSzNyG6g4V29uA0YpYiV0".
********/:1 Refused to execute script from 'https://********/dist/main.js?v=GV_ha01BR1m-ndY3XcDF5bTyZOFPUvT85ifae0YHuOk' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
********/:65 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://********/dist/vendor.css?v=8n-l57uq7xyf0Jb_Ri57dTH6WOTFUgxTidflzpQPI6Y".`

**Comment by Unimatrix0** [comment] 2017-11-26 19:49
I can confirm through my testing that this occurs on **older** versions of iOS, but is **not present** on iOS 11.

**Comment by spencercharest** [comment] 2017-11-27 15:59
@Unimatrix0 this is not the case for me. I am on the most up to date ios software (11.1.2) and I am still having this issue.

**Comment by euphoric85** [comment] 2017-11-29 03:59
I also get stuck at a blank white screen with "Loading..." while trying to access Ombi via nginx using both nginx config examples in the wiki.  This is with Chrome on Windows, Ombi DotNetCore 3.0.2408

**Comment by VossenTech** [comment] 2017-11-29 04:20
Ok, in the interest of keeping this issue on track, if you experience this issue on more platforms than just ios you have a different issue. If you experience this issue only via reverse proxy, and not via direct content (internal IP address) you have a different issue. If you have a different issue it should go in a different thread/issue. 

As far as this issue with ios goes I have experienced things similar to @Unimatrix0 , I can access the site from ios on 10.1 and 10.1.1 but nothing older than that, I cannot speak to newer versions as I keep my devices jailbroken and am not willing to upgrade.

@tidusjar  Are there any updates on this issue or any troubleshooting steps I can help you with?

**Comment by zin105** [comment] 2017-11-29 09:40
I think we should let @tidusjar make that call

**Comment by tidusjar** [comment] 2017-11-29 09:59
I agree with @VossenTech If this is an issue with your reverse proxy setup then it's not related.
I've not had time to look into this yet, but I'm pretty sure this is going to be due to limitations in older versions of the safari engine.

**Comment by goldenpipes** [comment] 2017-11-29 19:07
this seems to never load on Microsoft Edge on Windows 10 Mobile. ever. probably the edge mobile engine doesnt know how to load the page.

**Comment by cbarratt** [comment] 2017-12-02 19:35
I get page load issues too, iOS 11 Safari (no NGINX proxy invoked)

**Comment by andmillionaire** [comment] 2017-12-11 05:04
I have page loading issues as well. In iOS 10 not using a reverse proxy it will only get to LOADING page and sit there for a minute before "finishing" loading and still being stuck on the loading page. Happens in safari and chrome on mobile.

Not sure if it's related to the issue where I use duckdns so external users can access the page where they are experiencing around 5-8 minute page load times just to get signed in.

**Comment by tidusjar** [comment] 2017-12-11 08:10
You mention using a reverse proxy, can people try WITHOUT the proxy... Since I don't develop the proxy and i'm not aware of your setup.

**Comment by andmillionaire** [comment] 2017-12-12 17:09
Looks like newest update fixed the issue with it loading on mobile.

**Comment by goldenpipes** [comment] 2017-12-12 18:06
Still doesn't load on windows 10 mobile edge. No way to debug either. Bit it shares the engine with windows 10 desktop.

Maybe its angular that's isn't supported by MS. I'm gonna see what i can find out.

**Comment by tidusjar** [comment] 2017-12-12 20:24
I don't really have plans in supporting older browsers, latest of everything.

**Comment by disrupted** [comment] 2017-12-18 15:08
same here stuck at "Loading..." screen when accessing through nginx reverse proxy remotely. tested on macOS 10.13.2 w/ Safari 11.0.2 & Firefox 59.0a1 and Android 8.0 w/ Chromium 63

**Comment by nils1603** [comment] 2017-12-27 13:14
I am also using the nignx reverse proxy settings you provided in your wiki, without the reverse proxy it works like a charm.

**Comment by weirdcrap** [comment] 2017-12-31 12:43
I have no problems on Android 8 with Chrome or Firefox. Can be accessed through an NGINX reverse proxy or directly by IP:Port

**Comment by tidusjar** [comment] 2018-01-18 20:05
Closing since this seems to be resolved with the latest nginx config

**Closed by tidusjar** 2018-01-18 20:05 UTC

**Comment by sea3pea0** [comment] 2018-03-15 18:06
I am still having problems with edge, nginx and ombi v3. I am using a subdomain, this is my server block for ombi:

`### Ombi Server ###
server {
		listen 80;
		listen [::]:80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        include snippets/ssl-mysite.com.conf;
        include snippets/ssl-params.conf;

        server_name ombi.mysite.com;

		location / {
		    proxy_pass http://127.0.0.1:5000;
		    proxy_set_header Host $host;
		    proxy_set_header X-Forwarded-Host $server_name;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		    proxy_set_header X-Forwarded-Ssl on;
		    proxy_set_header X-Forwarded-Proto $scheme;
		    proxy_read_timeout  90;
		    proxy_redirect http://127.0.0.1:5000 https://$host;
		}

}`

It's working on chrome, firefox and internet explorer

**Comment by tidusjar** [comment] 2018-03-15 18:25
Edge is not supported

**Comment by Unimatrix0** [comment] 2018-03-15 18:25
@sea3pea0 what does that have to do with mobile browsers?

**Comment by sea3pea0** [comment] 2018-03-15 18:35
@Unimatrix0 Yea you're right I missed that, which lead me to realize it actually works fine on the Edge mobile browser but not on the desktop version of the browser
