### ISSUE TITLE
IMDB links are in incorrect format and failing

### ISSUE THREAD

**Issue by tyranian** [tidusjar/Ombi#3696] opened 2020-07-29 10:33 UTC
**Describe the bug**
When you click the title which then links to IMDB it returns a error 404 as the link is in the incorrect format

**To Reproduce**
1. Search for TV (such as Vikings)
2. Click on Title Link
3. IMDB link directs you to https://www.imdb.com/title/http://www.imdb.com/title/tt2306299//

**Expected behavior**
Link should be http://www.imdb.com/title/tt2306299/

**Desktop (please complete the following information):**
- OS:Windows
- Browser: Firefox & Chrome

**Ombi Version (please complete the following information):**
 - Version 3.0.5202

**Comment by Roxedus** [comment] 2020-08-12 23:51
Duplicate of #3523

**Closed by Roxedus** 2020-08-12 23:51 UTC
