### ISSUE TITLE
Emby direct item url not working, missing serverID

### ISSUE THREAD

**Issue by RobinMM** [tidusjar/Ombi#3515] opened 2020-04-28 09:55 UTC
**Describe the bug**
The URL that gets generated to open an item directly on Emby is not correct and lands up to blank page. 

**To Reproduce**
Open a request that is existing on Emby and click the 'View on Emby' button. It lands up to a page showing nothing.

**Expected behavior**
Item detail page succesfully loading.

**Additional context**
It seems the current URL is missing &serverId=XXXXX and not working because of that

**Comment by tidusjar** [comment] 2020-04-28 11:22
Duplicate of #3476

**Closed by tidusjar** 2020-04-28 11:22 UTC
