### ISSUE TITLE
After update to V2.1.1339 TV Requests still do not show

### ISSUE THREAD

**Issue by curlz620** [tidusjar/Ombi#1038] opened 2017-02-01 01:41 UTC
#### Ombi Version:
 V2.1.1339

#### Update Branch:
EAP

#### Operating System:
Windows Server 2008

#### Problem Description:I
 noticed that on a previous version an issue came up preventing the TV Show requests from appearing when selected. After updating to the newest release, which says it resolves the issue it still seems to be happening. I tried a clean install and cleared browser cache, but the issue persists.

####Logs
I pulled the logs below from the browser console.

```
{statusCode: 500, message: "Something went horribly, horribly wrong while servicing your request.",…}
details
:
"Nancy.RequestExecutionException: Oh noes! ---> System.FormatException: Input string was not in a correct format.
↵   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
↵   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
↵   at Ombi.UI.Modules.RequestsModule.<>c__DisplayClass47_0.<GetRootPath>b__3(SonarrRootFolder x) in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 297
↵   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
↵   at Ombi.UI.Modules.RequestsModule.<GetRootPath>d__47.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 297
↵   --- End of inner exception stack trace ---
↵   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)"
message
:
"Something went horribly, horribly wrong while servicing your request."
statusCode
:
500
```

**Comment by SuperPotatoMen** [comment] 2017-02-01 07:15
Pleas  Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs

**Comment by tidusjar** [comment] 2017-02-01 08:07
@curlz620 Can you send me your database please? Can you reset the admin password so I can log in?

tidusjar@gmail.com

**Comment by Rhainland** [comment] 2017-02-01 09:04
I also have this issue since the update, i can view movies just fine but tv shows throw error 500. 

Nothing in ombi logs about this

**Comment by tidusjar** [comment] 2017-02-01 09:08
@Rhainland You are welcome to send me your DB, I just need someones so I can reproduce this to fix it

**Comment by Rhainland** [comment] 2017-02-01 09:46
@tidusjar Any sensitive info in the db i should remove beforehand, or is everything in a settings file?

Regards

**Comment by tidusjar** [comment] 2017-02-01 09:50
It's all encrypted so I couldn't view it anyway

**Comment by Rhainland** [comment] 2017-02-01 09:51
@tidusjar Can you drop me an email or where do you want me to send this to you?

**Comment by d2dyno** [comment] 2017-02-01 09:53
Having the same issue. Email sent @tidusjar.

**Comment by curlz620** [comment] 2017-02-01 14:25
@tidusjar Just sent mine over now.

**Comment by Aireezz** [comment] 2017-02-01 20:52
I'm having the same issue, haven't sent my database over cause I see a few others already have. If you need me to I will though.

**Comment by tidusjar** [comment] 2017-02-01 20:57
Sorry guys, had a busy day today.

Got some free time now so i'll fix it. 

Is this happening only in the EAP? Or stable for some?

**Comment by Aireezz** [comment] 2017-02-01 20:58
I'm using EAP.

**Comment by d2dyno** [comment] 2017-02-01 20:59
@tidusjar I'm having this issue on stable.

**Comment by tidusjar** [comment] 2017-02-01 21:20
I've fixed this and merged it into the EAP branch. Can someone confim that it is now fixed?

**Comment by d2dyno** [comment] 2017-02-01 21:34
Switched to EAP,  still having this issue.

**Comment by tidusjar** [comment] 2017-02-01 21:35
@d2dyno What's the version in the settings?

**Comment by d2dyno** [comment] 2017-02-01 21:36
@tidusjar 2.1.1358

**Comment by tidusjar** [comment] 2017-02-01 21:40
@d2dyno You never told me the username or pass in the email :)

**Comment by d2dyno** [comment] 2017-02-01 21:50
@tidusjar sent.

**Comment by tidusjar** [comment] 2017-02-01 21:58
Is there any thing in your life because I think it could be a sonarr issue (connecting and getting the root path)

**Comment by Aireezz** [comment] 2017-02-01 22:01
Error messages: Invalid Path	Ombi.UI.Modules.ApprovalModule	Error	2/1/2017 3:54:49 PM
Error messages: Invalid Path	Ombi.UI.Modules.ApprovalModule	Error	2/1/2017 3:54:49 PM
Could not approve and send the TV Penny Dreadful to Sonarr!	Ombi.UI.Modules.ApprovalModule	Error	2/1/2017 3:54:49 PM
Invalid Path	Ombi.Api.SonarrApi	Error	2/1/2017 3:54:49 PM
Invalid Path	Ombi.Api.SonarrApi	Error	2/1/2017 3:54:49 PM
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract) <0x404726a0 + 0x00193> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) <0x40471e40 + 0x000a7> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x403ef380 + 0x000f7> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x403e9af0 + 0x001e3> in :0	Ombi.Api.SonarrApi	Error	2/1/2017 3:54:48 PM
Exception when calling AddSeries for Sonarr, Retrying 00:00:02	Ombi.Api.SonarrApi	Error	2/1/2017 3:54:46 PM
Error messages: Invalid Path	Ombi.UI.Modules.ApprovalModule	Error	2/1/2017 3:54:45 PM
Error messages: Invalid Path	Ombi.UI.Modules.ApprovalModule	Error	2/1/2017 3:54:45 PM
Could not approve and send the TV Sanctuary to Sonarr!	Ombi.UI.Modules.ApprovalModule	Error	2/1/2017 3:54:45 PM

**Comment by d2dyno** [comment] 2017-02-01 22:20
There's nothing in the logs about sonarr issues. Only CP (because I stopped using it). A test connectivity comes back clean on Sonarr.

**Comment by d2dyno** [comment] 2017-02-01 22:22
Think I fixed it. Had to hit 'submit' again on Sonarr (didn't change any fields). I'm seeing TV-Shows on the requests page now.

**Comment by tidusjar** [comment] 2017-02-02 08:03
Damn, I forgot about this.

Regarding the new feature to allow selecting the paths, you are required to go back into Sonarr Settings and resubmit your settings (for the new functionality to take place).

It shouldn't have broken the requests page though so I'll add some better error handling around that.

**Closed by tidusjar** 2017-02-02 08:03 UTC
Labels: EAP branch, in progress
