### ISSUE TITLE
Deleting request does not correctly refresh the list

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#2289] opened 2018-05-31 18:42 UTC
#### Ombi build Version:

V 3.0.3351

#### Update Branch:

develop
--

#### Media Sever:

Plex

#### Operating System:

docker

Linux 3.10.102 #15284 SMP Sat May 19 04:52:23 CST 2018

#### Problem Description:

Deleting a movie or tv request causes the list to not display any remaining requests until the browser is force refreshed 

#### Reproduction Steps:

Add several requests of movie or tv and then delete one.. The list will ether blank or show some of the remaining requests.. Forcing a browser refresh or navigating to a different section or back will restore the list to show the remaining requests.

**Comment by harrv** [comment] 2018-05-31 20:47
This appears to be a duplicate of issue 2288.

**Comment by anojht** [comment] 2018-06-01 07:45
Duplicate of #2288

**Closed by anojht** 2018-06-01 07:45 UTC
