### ISSUE TITLE
 StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:32400/library/metadata/0

### ISSUE THREAD

**Issue by cabagekiller** [tidusjar/Ombi#2707] opened 2018-12-30 01:30 UTC
#### Ombi build Version:

V 3.0.4036

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
 Ombi.Api.Api[1000]                                                                                                      StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:32400/library/metadata/0                    warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]                                                                           Exception thrown when attempting to cache the Plex Content in server Ralston                                      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.                                                                                                                         at Newtonsoft.Json.JsonTextReader.ParseValue()                                                                          at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)                                  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)                                                                                                   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)                               at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)              at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)                      at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77                      at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159                                                                                      at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 173                                                   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 132   


```

#### Problem Description:

It isn't updating if something isn't there

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment] 2018-12-30 08:36
Please include more information as I have no idea what your problem from this issue

**Comment by rcdailey** [comment] 2019-01-11 02:19
I got this on version 3.0.4119:


```
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server Nami
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.1.50:32400/library/metadata/101568
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server Nami
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessTvShow(PlexServers servers, Metadata show, HashSet`1 contentToAdd, Dictionary`2 contentProcessed) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 390
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 181
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 132
```

I simply clicked "Manually Run Recently Added Sync" under Settings -> Media Server -> Plex. I noticed that my requests are not being marked as available once they are grabbed my Radarr and added in Plex. For days they do not update. Maybe this is related?

Not sure what details to give up front. However, I can consistently reproduce this, so please let me know what additional information I may provide, or if you'd like me to run some tests. I'm using the LSIO docker container for Ombi.

**Comment by tidusjar** [comment] 2019-01-11 06:58
What is happening is ombi is expecting a JSON response but is getting back HTML. 

Meaning that it's not correctly configured eg. Auth token is incorrect

**Comment by rcdailey** [comment] 2019-01-11 12:44
I obtained a new auth token using these instructions: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

I then tried the sync again but had the same error

**Comment by rcdailey** [comment] 2019-01-12 01:05
@tidusjar: If you believe this is a configuration issue, could you please provide some diagnostic steps to verify exactly how the configuration is wrong? As mentioned in my previous reply, I tried a new auth token but this did not change the behavior. The other options are fairly straightforward, I do not see how they can be incorrect.

Thanks in advance for guidance.

**Comment by rcdailey** [comment] 2019-01-12 13:34
I am sure the credentials are correct. What I suspect is happening is the
content ID at the end of the URI is incorrect. Because when I do a full
sync, most of it works. There's just 1 or 2 URIs that fail. This is not an
issue with credentials at this point.

**Comment by tidusjar** [comment] 2019-02-03 14:47
That does seem plausible, since we are getting a Not found status code back from the server. 

Do you know when this happens does it stop processing the rest of the shows?

**Comment by clarenceb5** [comment] 2019-03-05 14:51
I've started receiving this message "StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1482473656" with no idea why or what it means?

**Comment by kdizzay** [comment] 2019-04-09 00:46
I am seeing the same behavior with NotFound status code - this is stopping processing of the rest of the shows as well.  I verified that credentials are correct by running a few curls to my server with the token to list libraries etc. This is on the latest develop but I suspect started happening after a certain request and/or media item was added to the plex library.

**Comment by kdizzay** [comment] 2019-04-09 16:22
So the only workaround here was to blow away the db and start from scratch - which I am ok doing, but would like to help as much as possible to debug and nail down the root cause for this. Obviously it's not fun when the software is chugging along just fine and one day a metadata search URI throws this exception and brings the rest of the processing to a grinding halt, but let me know if you need any further details. I have taken a backup of this db to be able to deploy in a test setup to reproduce the problem anytime.

**Closed** 2019-06-15 17:23 UTC
Labels: wontfix
