### ISSUE TITLE
Linux Automatic Updater broken. Looking for windows file

### ISSUE THREAD

**Issue by DirtyCajunRice** [tidusjar/Ombi#1792] opened 2017-12-12 04:57 UTC
#### Ombi build Version:

V 3.0.2459

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04.3

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-12-11 04:00:14.436 -08:00 [Warning] Failed to process the job '1006': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:30.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2017-12-11 04:00:50.062 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-12-11 04:01:00.627 -08:00 [Error] Failed to process the job '1006': an exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2017-12-11 10:00:17.848 -08:00 [Warning] Failed to process the job '1055': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:38.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2017-12-11 10:00:55.131 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-12-11 10:01:04.247 -08:00 [Error] Failed to process the job '1055': an exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2017-12-11 16:01:04.041 -08:00 [Warning] Failed to process the job '1105': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:28.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2017-12-11 16:01:33.329 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-12-11 16:02:07.794 -08:00 [Error] Failed to process the job '1105': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
```

#### Problem Description:

Looks like it is looking for an update file in a windows directory... which will obviously not work on linux haha

#### Reproduction Steps:

Enable automatic updater or try to manually update

**Comment by DirtyCajunRice** [comment] 2017-12-12 06:54
For now i whipped up a bash script to do it with the script arguments (Which i fixed for you in the wiki as they were misrepresented). For those that look for one after this:
```
#!/bin/bash

downloadlink="$1"
ombiroot="$3"
service="$5"

logging () {
echo "$@" >> /var/log/ombi_update.log
}

failed_logging () {
logging "Failed to " "$@" ". Exiting" && exit 1
}

logging "Downloading newest build from $downloadlink"
wget -q --directory-prefix=/tmp/ "$downloadlink" || failed_logging "download from $downloadlink"
logging "Stopping $service.service"
systemctl stop "$service" || failed_logging "stop $service.service"
logging "Unzipping new build over old build"
tar -xzf /tmp/linux.tar.gz -C "$ombiroot" || failed_logging "unzip to $ombiroot"
logging "Removing temporary download"
rm /tmp/linux.tar.gz || failed_logging "remove temporary download"
logging "Starting $service.service"
systemctl start "$service" || failed_logging "start $service.service"
```

https://github.com/tidusjar/Ombi/wiki/Update-Settings

**Comment by tidusjar** [comment] 2017-12-12 20:29
> Looks like it is looking for an update file in a windows directory

How did you work that out?

**Comment by DirtyCajunRice** [comment] 2017-12-12 22:50
Because right smack dab in the middle of the code it states multiple times:

>at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220

C:\ being the operative part XD

**Comment by goldenpipes** [comment] 2017-12-12 23:27
hmm... i get that same error on windows too.  my DIR for ombi is C:/ombi  not c:\projects\blahblahblah

curious

**Comment by tidusjar** [comment] 2017-12-13 08:29
@DirtyCajunRice That's just where the code was compiled and not where it's running. Closing this as it's a duplicate of #1460

**Closed by tidusjar** 2017-12-13 08:29 UTC
