### ISSUE TITLE
Question - Should user be logged out every time browser is closed?

### ISSUE THREAD

**Issue by m3ki** [tidusjar/Ombi#1206] opened 2017-03-01 17:18 UTC
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Running in docker rogueosb/docker-ombi

#### Mono Version (only if your not on windows)

OS:	Mono
System Version:	4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

This is more of a question:

It seems that ombi is not staying logged in.
If a tab is closed I will have to relogin with my plex credentials. 
Is this an intended behavior?

Is it possible to keep user logged in for extended period of time?

It is very painful,  to login every time especially if you're using a mobile device.

I do have following checked in Authentication page:
Enable User Authentication - Checked
Require users to login with their passwords - Checked

#### Reproduction Steps:

1. Open browser
2. Navigate to ombi URL 
3. User is presented with a landing page
4. Press continue
5. user is presented with login screen for plex credentials
6. Login
7. close the browser
8. reopen browser
9. Notice user is presented with a login screen again.
** expected behavior: user should still be logged in.

**Comment by diedrichg** [comment] 2017-03-04 16:29
Sounds like a browser cache, privacy setting clearing the credentials when leaving. Are you logged out from other sites when closing your browser?

**Comment by m3ki** [comment] 2017-03-04 16:42
No, this happens I different browsers (chrome, Firefox) both mobile and desktop. 

Other sites stay logged in. 

How long is the cookie expiration setting for ombi?

**Comment by FlynnLives** [comment] 2017-03-05 06:27
I have this "issue" as well, personally it doesn't bug me, I've considered it working as intended. Though it would be nice if Ombi would offer to save my password

**Comment by petwri** [comment] 2017-03-05 10:17
Same "problem" here on chrome. Would love to stay logged in, always entering the plex credentials is a pain in the ***.

**Comment by m3ki** [comment] 2017-03-06 21:54
I was looking through the code briefly and noticed that the controller code seems to support the "remember me" functionality for 7 days. 

But the form doesn't have that checkbox.

```
DateTime? expiry = null;
                if (Request.Form.RememberMe.HasValue)
                {
                    expiry = DateTime.Now.AddDays(7);
                }
```

But the Ombi/Ombi.UI/Views/UserLogin/Password.cshtml

Doesn't seem to have those form elements implemented.

Maybe one of the devs can comment on this.

Otherwise I might look into it myself at some point over the weekend.

**Comment by bobbintb** [comment] 2017-03-09 02:56
I'd like some sort of way to set this as well. I used gonative.io to make an app for Ombi for my family but they have to log back in occasionally. Is there some way to set a persistent cookie?

**Comment by FlynnLives** [comment] 2017-03-09 03:00
@m3ki that section is not in the current file but it would be nice if it made a return

https://github.com/tidusjar/Ombi/blob/master/Ombi.UI/Views/UserLogin/Password.cshtml

**Comment by tidusjar** [comment] 2017-03-09 08:29
Hi guys, 
@m3ki you are looking at the wrong controller :) The page you are referring to is the `UserLoginModule`

That doesn't support a "Remember me" but it can be added.

**Comment by bobbintb** [comment] 2017-03-27 20:40
Also, I think it would be nice if there were settings the admin could set for cookie sessions and such.

**Closed** 2017-07-04 22:46 UTC
Labels: enhancement
