### ISSUE TITLE
Plex/Ombi Sync - Series not synced, Movies are fine

### ISSUE THREAD

**Issue by lisifi** [tidusjar/Ombi#3095] opened 2019-07-30 20:23 UTC
**Describe the bug**
Plex - Ombi Sync is working for 50%
Movies get synced from Plex to Ombi, no errors there
Series do NOT get synced from Plex ... All series i have keep showing "Request" instead of "Available"
When i request a Movie --> Radarr picks it up
When i request a Series --> Sonar picks it up and downloads if needed

Only problem is Plex Content Sync, the Plex.IPlexEpisodeSync function, as seen in logs below

**To Reproduce**
1. Go to Plex Media Server
2. Click "Full Sync" (or Recently Added Sync)

**Expected behavior**
All series should be added, as the movies are.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
2019-07-30 22:03:53.855 +02:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2019-07-30 22:03:53.855 +02:00 [Information] Quartz scheduler version: 3.0.7.0
2019-07-30 22:03:53.856 +02:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2019-07-30 22:03:53.945 +02:00 [Debug] Batch acquisition of 0 triggers
2019-07-30 22:03:53.945 +02:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-07-30 22:04:23.737 +02:00 [Debug] Batch acquisition of 0 triggers
2019-07-30 22:04:49.484 +02:00 [Debug] Batch acquisition of 1 triggers
2019-07-30 22:04:50.741 +02:00 [Debug] Batch acquisition of 1 triggers
2019-07-30 22:04:50.761 +02:00 [Debug] Batch acquisition of 1 triggers
2019-07-30 22:04:50.781 +02:00 [Debug] Calling Execute on job Plex.IPlexContentSync
2019-07-30 22:04:50.799 +02:00 [Information] Starting Plex Content Cacher
2019-07-30 22:04:50.804 +02:00 [Information] Starting to cache the content on server "xxxxxxx"
2019-07-30 22:05:00.001 +02:00 [Debug] Calling Execute on job Emby.IEmbyContentSync
2019-07-30 22:05:00.002 +02:00 [Debug] Batch acquisition of 0 triggers
2019-07-30 22:05:00.023 +02:00 [Debug] Trigger instruction : NoInstruction
2019-07-30 22:05:02.883 +02:00 [Information] Starting EP Cacher
2019-07-30 22:05:02.884 +02:00 [Debug] Batch acquisition of 1 triggers
2019-07-30 22:05:02.885 +02:00 [Debug] Batch acquisition of 0 triggers
2019-07-30 22:05:02.885 +02:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2019-07-30 22:05:02.891 +02:00 [Error] Job Plex.IPlexContentSync threw an unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-07-30 22:05:02.907 +02:00 [Debug] Batch acquisition of 1 triggers
2019-07-30 22:05:02.960 +02:00 [Debug] Batch acquisition of 0 triggers
2019-07-30 22:05:02.907 +02:00 [Debug] Trigger instruction : DeleteTrigger
2019-07-30 22:05:02.961 +02:00 [Debug] Deleting trigger
2019-07-30 22:05:02.971 +02:00 [Error] Job Plex.IPlexContentSync threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2019-07-30 22:05:02.972 +02:00 [Debug] Trigger instruction : DeleteTrigger
2019-07-30 22:05:02.972 +02:00 [Debug] Deleting trigger
2019-07-30 22:05:02.977 +02:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2019-07-30 22:05:03.449 +02:00 [Debug] Trigger instruction : DeleteTrigger
2019-07-30 22:05:03.449 +02:00 [Debug] Deleting trigger

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Plex

**Additional context**

**Comment by Barbaro** [comment] 2019-08-09 09:35
Hi,

I have the save problem in the logs. Using the development branch doesn't solve it :'(

**Comment by tidusjar** [comment] 2019-08-09 10:21
I cannot see anything wrong with the code itself and cannot reproduce it with my Ombi instances.

The only way I am going to be able to easily fix this is if I can get a connection to your Plex server with my debug ombi instance to reproduce the issue. If you are happy with that please can you send me the details you use in your Ombi instance to connect to Plex (Settings > Media Server > Plex)
E.g. Hostname/IP address = This will need to be externally facing so I can connect
Port,
Auth Token
Also what Libraries you are monitoring if that is set.

**Comment by Barbaro** [comment] 2019-08-09 12:01
I dropped the required info at your gmail adress :)

**Comment by tidusjar** [comment] 2019-08-09 13:10
Thanks, I'll take a look at it as soon as I can

**Comment by trakus** [comment] 2019-08-12 03:46
I just went through a very similar troubleshooting process and I think I found the issue. Here's my post on the [/r/Ombi subreddit.](https://www.reddit.com/r/Ombi/comments/cp2w12/tv_shows_downloaded_prior_to_installing_ombi/ewney89?utm_source=share&utm_medium=web2x)

Long story short, it is likely syncing TV Shows correctly, but if you don't have full and complete seasons of ALL episodes, it will still show a Request button by default. If you click Request then Select, you should see the partial episodes marked as Available correctly. Hope this helps.

**Comment by Barbaro** [comment] 2019-08-12 07:12
I'm not sure your problem was the same, because here it stops the updating process with an error, when in your case it was finally ok.

**Comment by nadinio** [comment] 2019-09-13 15:33
I had the same issue as you and the same OS. I ended up abandoning Ubuntu Server 18.04 and installed it on Debian 9.2 and had no issues. Not sure if the OS is the key here, but that was my experience

**Comment by jeffk395** [comment] 2019-10-16 23:41
Any update on this issue as I am having the same. All movies are showing up correctly. Around half of all shows that I have are being reported as available, and the others are able to be requested. The ones that are showing up as request-able are full ended series with all episodes available. Even the ones that are missing a few episodes are showing as completely request-able. Running the server on macOS Mojave.

**Comment by tidusjar** [comment] 2019-10-17 07:24
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄

**Comment by M3th0s** [comment] 2019-11-02 00:12
Hey, just to report that I have the exact same issue.
Brand new clean install, movies have no issues refreshing, all connection reporting green across the board and all the correct libraries ticker under media server.
Movies have no problem showing correct status, tv shows however all have the "request" button. If you expand the button, it shows as request pending (in blue).
If you need anything from me to help resolve this, I will happily oblige:)
Thanks in advance!

**Comment by mattplotas** [comment] 2019-12-28 03:32
Having a similar issue but with Movies (I am using Emby however.) I can request movies and they get sent to my Radarr install just fine, however looking at the logs there it complains that the Source parameter cannot be null, as is reproduced [here](https://pastebin.com/raw/ENqbN4en) and below (can't seem to get the markdown right:)

``System.ArgumentNullException: Value cannot be null.  
Parameter name: source     
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x0000d] in <07a075f1d23046ea85ee23d71b0a0a37>:0 
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <07a075f1d23046ea85ee23d71b0a0a37>:0 
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo (System.Int32 TmdbId, NzbDrone.Core.Profiles.Profile profile, System.Boolean hasPreDBEntry) [0x0010b] in <28071e62f2f449e682962e05af20a3d7>:0 
  at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo (NzbDrone.Core.Movies.Movie movie) [0x0005d] in <28071e62f2f449e682962e05af20a3d7>:0 
  at NzbDrone.Core.Movies.RefreshMovieService.Execute (NzbDrone.Core.Movies.Commands.RefreshMovieCommand message) [0x00043] in <28071e62f2f449e682962e05af20a3d7>:0 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000ec] in <28071e62f2f449e682962e05af20a3d7>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <07a075f1d23046ea85ee23d71b0a0a37>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)``    
 
Here is what the log entries look like if it means anything: 
![error1](https://user-images.githubusercontent.com/2711558/71538290-2b2e3f00-28ee-11ea-8d17-755195a0bbb9.PNG)

I'd be happy to give you access to my Emby/Ombi instance if that would help in any way.

**Closed** 2020-03-04 19:19 UTC
Labels: wontfix
