### ISSUE TITLE
Feature Emby select which library to monitor

### ISSUE THREAD

**Issue by JosefineJensen** [tidusjar/Ombi#2885] opened 2019-03-12 17:41 UTC
It would be nice if it was possible to select which library to monitor for emby, like the feature that exist for plex servers

**Comment by xunil75** [comment] 2019-03-13 08:09
Please post it under [Feathub](http://feathub.com/tidusjar/Ombi) if doesn’t exist yet.

Thanks!

**Comment by tidusjar** [comment] 2019-03-13 08:28
@xunil75 Thanks but I asked him to post it here :)

**Comment by tidusjar** [comment] 2019-05-22 07:14
Duplicate of https://github.com/tidusjar/Ombi/issues/2389

**Closed by tidusjar** 2019-05-22 07:14 UTC
Labels: wontfix
