### ISSUE TITLE
Push notification getting repeated

### ISSUE THREAD

**Issue by jaywehner** [tidusjar/Ombi#3198] opened 2019-10-11 16:10 UTC
**Describe the bug**
Every day I get the same push notifications that the item is available. I get around 25 a day. I have to remove the request in order to stop the push notification from happening.
Please let me know what more information you need.
I am running on PhotoOS in docker using this docker: linuxserver/ombi
**To Reproduce**
No steps just have pushover notification setup.

**Expected behavior**
one time notification of receiving a new item.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
PhotonOS

**Ombi Version (please complete the following information):**

Version | 3.0.4680
-- | --
Branch | master
Github | https://github.com/tidusjar/Ombi
Discord | https://discord.gg/Sa7wNWb
Reddit | https://www.reddit.com/r/Ombi/
Issues | https://github.com/tidusjar/Ombi/issues
Wiki | https://github.com/tidusjar/Ombi/wiki
OS Architecture | X64
OS Description | Linux 4.19.72-2.ph3 #1-photon SMP Thu Sep 26 06:02:04 UTC 2019
Process Architecture | X64
Application Base Path | /opt/ombi

Media Server Plex

**Additional context**

**Comment by tidusjar** [comment] 2019-10-11 18:17
Duplicate of #2998

**Closed by tidusjar** 2019-10-11 18:17 UTC
