### ISSUE TITLE
Unable to complete Wizard

### ISSUE THREAD

**Issue by warburp** [tidusjar/Ombi#2205] opened 2018-04-27 20:26 UTC
#### Ombi build Version:

v3.0.3239

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4973

#### Operating System:
Win Server 2016 Datacenter

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-27 13:55:16.393 -04:00 [Debug] OK, signing into Plex
2018-04-27 13:55:16.460 -04:00 [Debug] This is our first time, good to go!
2018-04-27 13:55:17.139 -04:00 [Debug] Attempting to sign in to Plex.Tv
2018-04-27 13:55:17.140 -04:00 [Debug] Sign in successful
2018-04-27 13:55:17.140 -04:00 [Debug] Getting servers
2018-04-27 13:55:17.406 -04:00 [Debug] Adding first server
2018-04-27 13:55:17.553 -04:00 [Debug] Finished
2018-04-27 13:55:33.504 -04:00 [Debug] Adding first server
2018-04-27 13:57:02.110 -04:00 [Debug] OK, signing into Plex
2018-04-27 13:57:02.114 -04:00 [Debug] This is our first time, good to go!
2018-04-27 13:57:02.653 -04:00 [Debug] Attempting to sign in to Plex.Tv
2018-04-27 13:57:02.653 -04:00 [Debug] Sign in successful
2018-04-27 13:57:02.653 -04:00 [Debug] Getting servers
2018-04-27 13:57:02.818 -04:00 [Debug] Adding first server
2018-04-27 13:57:02.850 -04:00 [Debug] Finished
2018-04-27 14:01:20.773 -04:00 [Debug] OK, signing into Plex
2018-04-27 14:01:20.778 -04:00 [Debug] This is our first time, good to go!
2018-04-27 14:01:21.481 -04:00 [Debug] Attempting to sign in to Plex.Tv
2018-04-27 14:01:21.481 -04:00 [Debug] Sign in successful
2018-04-27 14:01:21.481 -04:00 [Debug] Getting servers
2018-04-27 14:01:21.654 -04:00 [Debug] Adding first server
2018-04-27 14:01:21.680 -04:00 [Debug] Finished
2018-04-27 15:09:00.953 -04:00 [Debug] OK, signing into Plex
2018-04-27 15:09:01.006 -04:00 [Debug] This is our first time, good to go!
2018-04-27 15:09:01.844 -04:00 [Debug] Attempting to sign in to Plex.Tv
2018-04-27 15:09:01.844 -04:00 [Debug] Sign in successful
2018-04-27 15:09:01.844 -04:00 [Debug] Getting servers
2018-04-27 15:09:02.083 -04:00 [Debug] Adding first server
2018-04-27 15:09:02.344 -04:00 [Debug] Finished
2018-04-27 15:11:57.606 -04:00 [Debug] OK, signing into Plex
2018-04-27 15:11:57.659 -04:00 [Debug] This is our first time, good to go!
2018-04-27 15:11:58.314 -04:00 [Debug] Attempting to sign in to Plex.Tv
2018-04-27 15:11:58.314 -04:00 [Debug] Sign in successful
2018-04-27 15:11:58.314 -04:00 [Debug] Getting servers
2018-04-27 15:11:58.556 -04:00 [Debug] Adding first server
2018-04-27 15:11:58.818 -04:00 [Debug] Finished


```

#### Problem Description:

I installed a brand new installation of Ombi on a new VM to migrate the service to a new server but when I fill out the Wizard with my Plex info I receive a pop up that says "Could not get Plex Admin information".  If I press skip it fails to create the admin account with "an error occurred you might want to put this on github"

#### Reproduction Steps:

Install a fresh on Win Server 2016 and try to setup.

**Comment by tidusjar** [comment] 2018-04-27 20:37
Duplicate of #2119

**Closed by tidusjar** 2018-04-27 20:37 UTC
