### ISSUE TITLE
Error's v4

### ISSUE THREAD

**Issue by ne0ark** [tidusjar/Ombi#3732] opened 2020-08-24 20:40 UTC
**Describe the bug**
Lag/No Response from UI

**Logs (Logs directory where Ombi is located)**

```
[Error] Exception when adding new Movie "<movie>"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Guid', line 1, position 6385.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in /home/vsts/work/1/s/src/Ombi.Api.Plex/PlexApi.cs:line 160
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 282
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu

**Ombi Version (please complete the following information):**
 - Version 4.0.454.0
- Media Server Plex

**Additional context**
Error seems to happen for all the movies.

**Comment by tidusjar** [comment] 2020-08-24 20:54
Are you using the Plex beta ?

**Comment by ne0ark** [comment] 2020-08-25 15:01
Yes using plex beta and the new plex movie agent.

**Comment by PotatoQuality** [comment] 2020-08-26 11:55
@ne0ark At this time ombi doesn't support the new plex movie agent.

**Comment by ne0ark** [comment] 2020-08-26 14:34
Thnx do you know what changed? Is it a quick fix?

**Comment by sienar1** [comment] 2020-08-26 17:18
Also having this issue with Ombi. The new plex movie agent solved a lot of metadata issues for me, so I don't plan to go back. The old agent is being moved to legacy and will be deprecated eventually. Any plans on working on whatever change is needed to support the new agent?

**Comment by sienar1** [comment] 2020-08-26 17:19
Also, this appears to be dupe of https://github.com/tidusjar/Ombi/issues/3692

**Closed** 2020-08-26 17:42 UTC
