### ISSUE TITLE
Angular Error: `req is not defined`

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/Ombi#1683] opened 2017-11-05 17:48 UTC
#### Ombi build Version:

V 3.0.2314-PR

#### Update Branch:

Open Beta

#### Media Sever:

NA

#### Media Server Version:

NA

#### Operating System:

UnRaid Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-11-05 12:47:02.082 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-05 12:47:06.390 -05:00 [Information] Hangfire SQL objects installed.
2017-11-05 12:47:06.439 -05:00 [Information] Starting Hangfire Server
2017-11-05 12:47:06.446 -05:00 [Information] Using job storage: 'SQLite Server: /config/Ombi.db'
2017-11-05 12:47:06.446 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-05 12:47:06.446 -05:00 [Information]     Worker count: 1
2017-11-05 12:47:06.447 -05:00 [Information]     Listening queues: 'default'
2017-11-05 12:47:06.447 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-05 12:47:06.447 -05:00 [Information]     Schedule polling interval: 00:00:15
```

#### Problem Description:

![image](https://user-images.githubusercontent.com/12055335/32417399-34f00332-c227-11e7-8d49-bf7494aeb556.png)

#### Reproduction Steps:

Pull fresh docker and start.

**Comment by tidusjar** [comment] 2017-11-05 18:31
That happens on the first page?

**Comment by Codehhh** [comment] 2017-11-05 18:46
Yes, before initial setup

**Comment by weirdcrap** [comment] 2017-11-05 19:14
I am also experiencing this issue.

**Comment by daymanbpi** [comment] 2017-11-05 19:51
pulled fresh docker. latest. 
same. webpage is just stuck on loading... screen.

**Comment by that1guy** [comment] 2017-11-06 03:50
Confirmed.  Same issue here.

**Comment by tidusjar** [comment] 2017-11-06 08:45
Looks like this is only happening in the PR builds... How is everyone updating?

**Comment by tidusjar** [comment] 2017-11-06 10:18
Ok i'll speak to the lsio team.

I've currently disabled pull requests from building on AppVeyor so that should prevent this until it's fixed in the container.

I've kicked off a new build so if you guys update it should now be fine.

**Comment by tidusjar** [comment] 2017-11-06 13:51
Nope, looks like it's still an issue

**Comment by tidusjar** [comment] 2017-11-06 13:56
https://github.com/angular/angular-cli/issues/8359

**Comment by weirdcrap** [comment] 2017-11-06 17:46
After a fresh docker pull mine now seems to be working...

**Comment by gilbN** [comment] 2017-11-06 18:02
Working for me too

**Comment by Codehhh** [comment] 2017-11-06 18:03
tidusjar created a workaround for the time being as it's an external error
with angular 5.

**Comment by Codehhh** [comment] 2017-11-08 11:30
@tidusjar the angular-cli issue is closed, just need to update uglify-es to 3.1.8

**Comment by PotatoQuality** [comment] 2017-11-08 17:07
@Codehhh thanks for the headsup. 
I saw your code push on this one @tidusjar . Can we close this issue?

**Closed** 2017-11-08 22:30 UTC
Labels: bug / issue, External problem, in progress
