### ISSUE TITLE
Sync Individual Libraries for Emby Like Plex

### ISSUE THREAD

**Issue by LindsayCole** [tidusjar/Ombi#2361] opened 2018-06-29 21:57 UTC
As discussed via Discord.

Would like the ability to sync individual or no libraries from Emby.

This would help with the load issues experienced while syncing Ombi against a large Emby library.

**Comment by tidusjar** [comment] 2018-07-27 14:30
dupe of #2389

**Closed by tidusjar** 2018-07-27 14:30 UTC
Labels: enhancement
