### ISSUE TITLE
Requests page: Poster url error

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/Ombi#1533] opened 2017-10-05 14:54 UTC
![image](https://user-images.githubusercontent.com/12055335/31233740-477e6fe0-a9bb-11e7-999c-82ec4d8ac4b8.png)
![image](https://user-images.githubusercontent.com/12055335/31233839-7a0156f8-a9bb-11e7-9afc-25107c772822.png)

- [ ] Fix posters for movie requests

**Comment by tidusjar** [comment] 2017-10-06 07:13
Fixed this from happening again, current broken ones will not be fixed. Also I wouldn't recommend Death Note, it was an awful adaptation.

**Comment by Codehhh** [comment] 2017-10-06 10:08
I've heard the same but still wanted it grabbed 👍

**Comment by Scorcher7986** [comment] 2017-10-09 04:00
@tidusjar is see the issue is fixed, but has an update for it been pushed yet?

This problem still occurs on for me on the latest 3.0.2096 for newly added movies

**Comment by tidusjar** [comment] 2017-10-13 21:08
Cannot reproduce,

Can anyone provide some reproduction steps?

**Comment by goldenpipes** [comment] 2017-10-13 23:21
not sure how its happening but it happened to me just now as well...
![image](https://user-images.githubusercontent.com/6140137/31569773-48aeec08-b043-11e7-95de-65d7c2afa8bc.png)

**Comment by goldenpipes** [comment] 2017-10-13 23:34
obviously whatever agent is pulling the images from TMDB in this case:
`https://image.tmdb.org/t/p/w150/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg`

should be pulling:

`https://image.tmdb.org/t/p/w150/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg` or
`https://image.tmdb.org/t/p/w300/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg`

so its trying to pull the image w150 and w300 but w300 twice.  Wierd.

**Comment by Scorcher7986** [comment] 2017-10-14 08:03
They all follow the same format, but some even have more /w300/ links than others. For example, here's 4 posters I randomly picked out from the error log that fail loading:

```
https://image.tmdb.org/t/p/w150/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/dN9LbVNNZFITwfaRjl4tmwGWkRg.jpg
https://image.tmdb.org/t/p/w150/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/mUjWof8LHDgCZC9mFp0UYKBf1Dm.jpg
https://image.tmdb.org/t/p/w150/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg
https://image.tmdb.org/t/p/w150/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/p64TtbZGCElxQHpAMWmDHkWJlH2.jpg
```

They all start with `https://image.tmdb.org/t/p/w150/`, then two have `https://image.tmdb.org/t/p/w300/` appear 4 times, one has it appear 3 times, and the last only 2 times. Very weird.

**Comment by Scorcher7986** [comment] 2017-10-14 08:06
I wonder if a temporary workaround in the code would be to trim out all the `https://image.tmdb.org/t/p/w300/` and `https://image.tmdb.org/t/p/w150/` to only store the image filename, then hardcode one of the prefixes in when loading. They seem to be interchangable, only the /w150/ version being smaller than the /w300/.

**Comment by Scorcher7986** [comment] 2017-10-14 10:16
So I've cheated a bit by creating a hacky javascript workaround since I know very little about C#. I've edited the file `/ombi/Views/Home/Index.cshtml` which seems to be the base template document used by ombi and added the following script at the end:
```
<script type="text/javascript">
    window.addEventListener('error', function(e) {
        var allImages = document.getElementsByTagName("img");
                for (var i = 0, len = allImages.length; i < len; ++i) {
                    if (allImages[i].alt == "poster") {
                        allImages[i].src.replace("https://image.tmdb.org/t/p/w300/", "");
                        allImages[i].src = allImages[i].src.replace(new RegExp("https://image.tmdb.org/t/p/w300/", 'g'), "");
                    }
                };
    }, true);
</script>
```

It listens for an error to be logged, creates an array of all images with alt text 'poster', and then cycles through them using regex to remove any matches of "https://image.tmdb.org/t/p/w300/" in the src tag. Works flawlessly as far as I can tell on desktop and mobile.

Whilst not a permant solution and probably not the most efficient, it works well enough as a temporary fix and I'll be using it in the meantime 🙂

**Comment by tidusjar** [comment] 2017-10-14 20:43
Can someone with this issue create me a user and send me their database? tidusjar@gmail.com

**Comment by tidusjar** [comment] 2017-10-14 20:51
Also this is still happening on the latest version?

**Comment by Scorcher7986** [comment] 2017-10-15 03:33
Updated from 3.0.2099 to 3.0.2113 - issue seems to be fixed now ¯\_(ツ)_/¯

Is there any way to manually repair the posters of movies added prior to the fix?

**Comment by tidusjar** [comment] 2017-10-15 08:14
Unfortunately not. Unless you modify the data in the database

**Closed by tidusjar** 2017-10-15 08:14 UTC
Labels: bug / issue, V3
