### ISSUE TITLE
Quality and Root Path Preferences per user, when clicked nothing shows up. 

### ISSUE THREAD

**Issue by Fire-Rage** [tidusjar/Ombi#2565] opened 2018-10-05 15:34 UTC
#### Ombi build Version:

V 3.0.3795

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.8.5395

#### Operating System:

unRAID 6.6.1 (linux)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-10-04 08:52:30.560 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/335983?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-04 08:52:30.616 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/335983?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-04 08:52:30.700 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/348350?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-04 08:52:30.721 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/439079?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-04 08:52:30.723 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/348350?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-04 08:52:30.738 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/439079?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-04 08:52:30.890 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/299536?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-04 08:52:30.916 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/299536?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-04 08:52:30.956 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/363088?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-04 08:52:30.971 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/363088?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-04 08:59:22.628 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-10-04 08:59:35.456 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-10-04 12:24:08.802 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/447200?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-04 12:24:08.819 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/351286?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-10-04 12:24:08.830 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/400155?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-04 12:24:08.834 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/447200?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-04 12:24:08.837 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/351286?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-04 12:24:08.853 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/400155?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

quality and root path preferences per user isnt working, when click just expands and shows nothing. sonnar and radarr are enabled.

#### Reproduction Steps:

i confirm that sonarr and radarr are enabled.  tried to get support on discord and tidusjar told me to raise it up to github. i also just installed ombi on my other unraid server, fresh install.  enabled radarr and connected it.  still had the same problem.

**Comment by tidusjar** [comment] 2018-10-07 16:45
I cannot reproduce this. can you clear your browser cache and try again?

**Comment by tidusjar** [comment] 2018-10-08 09:33
Fixed in develop

**Closed by tidusjar** 2018-10-08 09:33 UTC
