### ISSUE TITLE
Request via radarr not working

### ISSUE THREAD

**Issue by lucidonlinenet** [tidusjar/Ombi#1439] opened 2017-06-22 17:08 UTC
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10 

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Radarr.RadarrAddMovie' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, Uri baseUrl, Boolean searchNow) in C:\projects\requestplex\Ombi.Api\RadarrApi.cs:line 128

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Ombi will no longer add movie requests to radarr since the update yesterday (radarr version 0.2.0.778 20th June. 

#### Reproduction Steps:

Any attempt to request a movie

**Comment by lucidonlinenet** [comment] 2017-06-22 17:11
```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Radarr.RadarrAddMovie' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, Uri baseUrl, Boolean searchNow) in C:\projects\requestplex\Ombi.Api\RadarrApi.cs:line 128

**Comment by tidusjar** [comment] 2017-06-22 20:53
Looks like the Radarr API has changed. I'll look at fixing this tomorrow

**Comment by tidusjar** [comment] 2017-06-23 20:54
Interesting, I cannot reproduce this!

Does this happen every time or only with certain titles?

**Comment by lucidonlinenet** [comment] 2017-06-23 20:56
Every time. I've tried rebooting my system, fresh install of radarr and ombi. Nothing fixes it.

**Comment by PR3SIDENT** [comment] 2017-06-24 00:08
I am also having this issue after the last update.

Logs: `Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Radarr.RadarrAddMovie' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, Uri baseUrl, Boolean searchNow) in C:\projects\requestplex\Ombi.Api\RadarrApi.cs:line 128`

**Comment by IBeRamen** [comment] 2017-06-24 02:14
Same issue.

Ombi Version: v2.2.1678

Update Branch: Stable

Media Sever: Plex

Media Server Version 1.7.3.3937

Operating System: Linux (Ubuntu 16.04)

Logs: Same as above.

**Comment by tidusjar** [comment] 2017-06-24 20:42
I need to see the JSON response from Radarr... This does not happen for myself which is strange, I'm also running the develop branch.

Is anyone familiar with Postman? Or can I jump onto someones VM/Machine to see the response?

**Comment by PR3SIDENT** [comment] 2017-06-24 21:23
@tidusjar here you go man.

```System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 37```

**Comment by tobsen987** [comment] 2017-06-25 07:54
I am on the latest nightly of Radarr and it works fine after I added the webroot in the settings of Ombi.

**Comment by lucidonlinenet** [comment] 2017-06-25 10:51
So that fixed it. Looking at the radarr documentation they updated the api URL with the last update.

**Comment by PR3SIDENT** [comment] 2017-06-25 14:48
Not sure I understand what you guys changed, what am I missing here?

![image](https://user-images.githubusercontent.com/11300559/27517078-626f86ca-598b-11e7-89f9-781625d3120d.png)

**Comment by tobsen987** [comment] 2017-06-25 15:17
You have to enter your Radarr Base URL if you have set one in Radarr itself.

**Comment by PR3SIDENT** [comment] 2017-06-25 15:24
Nice, thanks that worked. I think we can close this issue out @tidusjar.

**Comment by tidusjar** [comment] 2017-06-25 16:01
Ahh.. that's why it was working for me!

**Closed by tidusjar** 2017-06-25 16:01 UTC

**Comment by h3artbl33d** [comment] 2017-06-26 17:23
Hate to 'reopen' this issue. What @tobsen987 said, actually worked. But, if the 'base URL' isn't filled in, Ombi gives a notification that it has been added - while actually, Radarr refused it. Is it possible to throw an error when this happens?

**Comment by tidusjar** [comment] 2017-06-26 17:43
I closed it since I plan to do no further work on Ombi V2.

I'm currently consentrating on the rewrite. More time I spend on V2 the
less time I get on V3 :)

**Comment by alneven** [comment] 2017-08-29 20:27
"You have to enter your Radarr Base URL if you have set one in Radarr itself."

This hint would be great on the interface 
I was looking back and forth until I found this one-liner

Thanks!

**Comment by tidusjar** [comment] 2017-08-29 21:12
Yeah i'm planning to improve the admin stuff with "hints". V2 doesn't explain itself very well
