### ISSUE TITLE
Every request says could not be added, added into requests queue and will keep retrying

### ISSUE THREAD

**Issue by atg22896** [tidusjar/Ombi#3946] opened 2020-12-28 23:11 UTC
**Describe the bug**
When a request is added, this notification is sent in addition to the normal approval notification. The request is actually immediately added and is sent as expected.
This has not always happened, started happening like a month ago when I updated image. I don't know what previous image was before, but it has next been fixed with any image updates.

**To Reproduce**
1. Make request
2. Get this notification

**Expected behavior**
When adding it a request, it will do so without this error message.

**Logs (Logs directory where Ombi is located)**
[ombi.log](https://github.com/tidusjar/Ombi/files/5749062/ombi.log)

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
https://github.com/linuxserver/docker-ombi/issues/82

**Comment by tidusjar** [comment] 2020-12-29 08:13
Version of radarr?

**Comment by spenceapalooza** [comment] 2020-12-29 16:02
same issue here

Radarr version: 3
ombi: 3.0.5223
Platform: windows 10 pro VM 

2020-12-29 06:30:41.153 -08:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request)
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 417
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 122
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24


Thanks for any help! ombi has saved me so much manual labor!

**Comment by atg22896** [comment] 2020-12-29 16:04
> Version of radarr?

Version 3, as it is the current stable version.

**Comment by jrh3k5** [comment] 2021-01-01 16:29
I'm experiencing this, too. I tried firing up Fiddler on the server to see if I could capture the traffic between Ombi and Radarr and understand what's changed about Radarr's response structure, but it wasn't seeing anything. This article suggests that the application may be configured to not use proxies:

https://docs.telerik.com/fiddler/Observe-Traffic/Troubleshooting/NoTrafficToLocalhost#problem-traffic-sent-to-httplocalhost-or

I poked around in Ombi's settings menus to see if there was a proxy option and couldn't identify one - have I missed something obvious? Or, if it's not a currently-available feature, could proxy support be added (unsure of the difficult of adding that in)? Or is it something entirely different from what I've postulated above?

**Comment by norrisp90** [comment] 2021-01-02 14:59
+1, experiancing the same issue re retry queue notification but the request has actaully been added correctly.

**Comment by RyanAStrouse** [comment] 2021-01-05 03:47
Same issue

**Comment by fmsidoe** [comment] 2021-01-06 15:23
+1 same issue, same notification, adds correctly. Also when downloaded it does not mark it as available while the settings and connection to Plex are working

**Comment by blacktirion** [comment] 2021-01-06 16:23
Confirmed. Running Radarr V3 and Ombi. It didn't happen on previous version of Radarr. Probably a code change in Radarr API that Ombi is not keying on.

**Comment by tidusjar** [comment] 2021-01-08 19:30
For Radarr 3 to work, you need to be running Ombi Develop or Ombi v4

**Comment by atg22896** [comment] 2021-01-08 19:52
> For Radarr 3 to work, you need to be running Ombi Develop or Ombi v4

Is V4 stable? I'm using Linux server.io docker image currently - can I just change to V4 image and DB and everything will work fine? Or will I need to do some sort of update process?

**Comment by slywoolmango** [comment] 2021-01-12 19:41
I'm in the same boat as @atg22896 with using the Linux server.io docker image. Would love to know if I can go ahead and upgrade to V4 to get past this issue. Thanks for yall your hard work!

**Comment by jsuttinger** [comment] 2021-01-13 02:53
> I'm in the same boat as @atg22896 with using the Linux server.io docker image. Would love to know if I can go ahead and upgrade to V4 to get past this issue. Thanks for yall your hard work!

I am running Ombi 4.0.956.0 and have had this issue for the last few days.

**Comment by jsuttinger** [comment] 2021-01-15 02:25
I have collected some logging during the failure. 
Ombi 4.0.956.0 and 4.0.975.0 
Radarr: 3.0.1.4259

```
2021-01-14 18:16:40.011 -05:00 [Error] Failed caching queued items from Radarr
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
   at Ombi.Api.Radarr.RadarrApi.GetMovies(String apiKey, String baseUrl)
   at Ombi.Schedule.Jobs.Radarr.RadarrSync.Execute(IJobExecutionContext job)
```
Logs after testing radarr connectivity from Settings > Movies > Radarr

```
021-01-14 21:11:40.014 -05:00 [Error] Exception when trying to cache Sonarr
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
   at Ombi.Api.Sonarr.SonarrApi.GetSeries(String apiKey, String baseUrl)
   at Ombi.Schedule.Jobs.Sonarr.SonarrSync.Execute(IJobExecutionContext job)

2021-01-14 21:16:31.035 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```
Connectivity to Sonarr is also failing.

**Comment by tidusjar** [comment] 2021-01-18 09:33
Ombi is timing out when trying to call the Sonarr/Radarr API's. It's taking over 100 seconds as there's something wrong with your setup.

Closing the issue as the problem is using V3 master with V3 Radarr which is not compatible, either use V3 develop or v4.

**Closed by tidusjar** 2021-01-18 09:33 UTC

**Comment by atg22896** [comment] 2021-01-18 15:22
> Ombi is timing out when trying to call the Sonarr/Radarr API's. It's taking over 100 seconds as there's something wrong with your setup.
> 
> Closing the issue as the problem is using V3 master with V3 Radarr which is not compatible, either use V3 develop or v4.

@tidusjar Can I upgrade my docker image directly from V3 to V4? Will there be no DB or upgrade issues?

**Comment by tidusjar** [comment] 2021-01-18 15:33
Yes it will be fine, just take a backup of your databases just incase

**Comment by atg22896** [comment] 2021-01-18 16:37
> Yes it will be fine, just take a backup of your databases just incase

Ok getting console errors in Chrome after upgrading.
![Screen Shot 2021-01-18 at 11 36 21 AM](https://user-images.githubusercontent.com/33287665/104941733-6f6d0100-5981-11eb-96d1-0e8fea13d9df.png)
Here is Ombi logs
```
We are running on http://*:3579
/opt/ombi
info: Ombi.Schedule.Jobs.Emby.EmbyEpisodeSync[0]
      Emby Episode Sync Finished - Triggering Metadata refresh
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Starting the Metadata refresh
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Movie The Town EXTENDED (2010) [1080p] does not have a ImdbId or TheMovieDbId, so rechecking emby
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Checking server Praetorian for upto date metadata
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Movie The Town EXTENDED (2010) [1080p] does not have a ImdbId or TheMovieDbId, so rechecking emby
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Checking server Praetorian for upto date metadata
fail: Ombi.Api.Api[1000]
      StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: http://192.168.1.5:8096/emby/users/af91b6a3a3b54e05b6d1f488bb03fe0a/items/26
fail: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Exception when refreshing the Metadata Refresh
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
         at Ombi.Api.Emby.EmbyApi.GetInformation[T](String mediaId, String apiKey, String userId, String baseUrl)
         at Ombi.Api.Emby.EmbyApi.GetMovieInformation(String mediaId, String apiKey, String userId, String baseUrl)
         at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartEmbyMovies(EmbySettings settings)
         at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartEmby(EmbySettings s)
         at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.Execute(IJobExecutionContext job)
```
