### ISSUE TITLE
Ombi not adding certain unreleased shows to sonarr

### ISSUE THREAD

**Issue by XantherBanter** [tidusjar/Ombi#2872] opened 2019-03-07 04:56 UTC
**Describe the bug**
Ombi is not adding certain unreleased shows to sonarr such as After Life. Other unreleased TV shows were processed as expected.

**To Reproduce**
1. Logon to Ombi
2. Click on TV Shows
3. Search for any upcoming TV show

**Expected behavior**
Ombi should process the request and automatically added to Sonarr.

**Screenshots**

From Settings ---> System ---> Failed Requests (Error Description)

![heh](https://user-images.githubusercontent.com/28868448/53932956-27e27200-4094-11e9-8adb-16a5376c2af2.jpg)

There is another error description where it says "Unknown Address"

Discord Webhook Output

![lol](https://user-images.githubusercontent.com/28868448/53933025-6d06a400-4094-11e9-8d4b-b9178857f462.jpg)

**Logs (Logs directory where Ombi is located)**

[log-20190307.txt](https://github.com/tidusjar/Ombi/files/2939567/log-20190307.txt)

**Desktop (please complete the following information):**
 - Debian 4.9.30 (Shared seedbox)
 - Running on Docker

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server - Plex

**Comment by tidusjar** [comment] 2019-03-07 08:51
Duplicate of #2871

**Closed by tidusjar** 2019-03-07 08:51 UTC
