### ISSUE TITLE
Nothing happens when clicking "Select" on any TV Series request

### ISSUE THREAD

**Issue by Adouken** [tidusjar/Ombi#1848] opened 2018-01-03 22:36 UTC
#### Ombi build Version:

V 3.0.2553

#### Update Branch:

Open Beta

#### Media Sever:

Plex/

#### Operating System:

unraid docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

We are running on

i
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Start installing Hangfire SQL objects...
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Hangfire SQL objects installed.
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Starting Hangfire Server
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using job storage: 'SQLite Server: /config/Schedules.db'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using the following options for Hangfire Server:
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Worker count: 1
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Listening queues: 'default'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Shutdown timeout: 1.00:00:00
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Schedule polling interval: 00:00:15
Hosting environment: Production
Content root path: /app/ombi
Now listening on: http://0.0.0.0:3579
Application started. Press Ctrl+C to shut down.
[41m[30mfail[39m[22m[49m: Ombi.Api.Api[1000]
StatusCode: Forbidden, Reason: Site Disabled
[41m[30mfail[39m[22m[49m: Ombi.Api.Api[1000]
StatusCode: Forbidden, Reason: Site Disabled
[41m[30mfail[39m[22m[49m: Ombi.Api.Api[1000]
StatusCode: Forbidden, Reason: Site Disabled
```

#### Problem Description:

When trying to download a specific episode after clicking the select button nothing happens

#### Reproduction Steps:

Tried deleting docker and starting again.

**Comment by tidusjar** [comment] 2018-01-04 07:58
Anything in the browsers console? F12

**Comment by Adouken** [comment] 2018-01-04 10:40
There are a few errors appearing when loading the search of a TV series.

VM1198:1 GET http://192.168.0.18:3579/api/v1/search/Tv/info/0/Tree 500 (Internal Server Error)

vendor.js?v=zO-p-yXBv7xvaFHp6pPIgDdVgqVz3JWtL39OMPBXr48:1 ERROR e {headers: t, status: 500, statusText: "Internal Server Error", url: "http://192.168.0.18:3579/api/v1/search/Tv/info/0/Tree", ok: false, …}

Seem to be the two errors.

I'll attach the full log. 
[log.txt](https://github.com/tidusjar/Ombi/files/1603073/log.txt)

**Comment by tidusjar** [comment] 2018-01-04 15:29
Is there any logs in your `/logs` foldeR?

**Comment by Adouken** [comment] 2018-01-04 16:24
Here is the log from the log folder:

[log-20180104.txt](https://github.com/tidusjar/Ombi/files/1603953/log-20180104.txt)

Thanks for your help by the way.

**Comment by infamouswb** [comment] 2018-01-04 23:15
I am having the same issue. the only option working it to download the whole show vs selecting which season.

**Comment by Fma965** [comment] 2018-01-04 23:16
i'm also having this same issue. (but you already know as i mentioned it on discord)

**Comment by infamouswb** [comment] 2018-01-05 05:09
@tidusjar The issue is still present with the latest update. Similar on also that if you click on report an issue, it does not go anywhere. Clicking the button does not load anything.

**Comment by tidusjar** [comment] 2018-01-05 19:48
Everything seems to work fine on the latest version.

**Comment by Doginal** [comment] 2018-01-05 23:36
@tidusjar what is the current version for v3? I'm on Version 3.0.2553 and "checking for updates" saying i am on the latest update. 
I am seeing ```GET /api/v1/Job/updateCached/ 500 (Internal Server Error)``` and ```GET /api/v1/search/Tv/info/0/Tree 500 (Internal Server Error)``` in chrome dev tools also.

**Comment by tidusjar** [comment] 2018-01-06 11:27
That's a different error @Doginal 

Please upgrade, there is a known issue where we are not checking for the latest version due to my service being down. 

Can you check your log files for the related error.

**Comment by tidusjar** [comment] 2018-01-06 11:28
I'm closing this for now as it no longer seems an issue on the latest version.

**Closed by tidusjar** 2018-01-06 11:28 UTC

**Comment by dejected1** [comment] 2018-01-07 16:43
I still have this issue. I had this issue on 2540, updated to 2593 and still have the issue. Nothing shows up in console. here is the log file: 

[log-20180107.txt](https://github.com/tidusjar/Ombi/files/1609961/log-20180107.txt)

**Comment by infamouswb** [comment] 2018-01-07 20:36
Its working fine for me the latest update. Have you tried another browser?

**Comment by dejected1** [comment] 2018-01-07 20:49
right-o. i cleared cookies and temp files in chrome and it started working. should have tried that first.
