### ISSUE TITLE
Ombi on Windows will not import any new Plex users

### ISSUE THREAD

**Issue by csc0ttbrown** [tidusjar/Ombi#3620] opened 2020-06-16 13:54 UTC
**Describe the bug**
Title says it all. New Plex users are not auto-imported into Ombi. Additionally, the "Run Importer" button in the User Importer tool does nothing.

**To Reproduce**
1. Go to Ombi Settings.
2. Click on Configuration and then User Importer.
3. Look and see that all Plex users are not accounted for.
4. Hit "Run Importer" button. Nothing happens.

**Expected behavior**
Users should auto-import as a scheduled task, I believe (at least, that's what they've been doing since I set up Ombi). Even if that weren't the case, the "Run Importer" button should manually import any unaccounted for users.

**Logs (Logs directory where Ombi is located)**
2020-06-16 09:49:46.449 -04:00 [Debug] Calling Execute on job Emby.IEmbyUserImporter
2020-06-16 09:49:46.449 -04:00 [Debug] Trigger instruction : DeleteTrigger
2020-06-16 09:49:46.449 -04:00 [Debug] Batch acquisition of 0 triggers
2020-06-16 09:49:46.449 -04:00 [Debug] Deleting trigger
2020-06-16 09:49:46.449 -04:00 [Debug] Calling Execute on job Plex.IPlexUserImporter
2020-06-16 09:49:47.024 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/friends/all/
2020-06-16 09:49:47.025 -04:00 [Error] Job Plex.IPlexUserImporter threw an unhandled Exception: 
System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 93
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 200
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 63
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2020-06-16 09:49:47.025 -04:00 [Error] Job Plex.IPlexUserImporter threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 93
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 200
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 63
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 93
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 200
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 63
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2020-06-16 09:49:47.025 -04:00 [Debug] Trigger instruction : DeleteTrigger
2020-06-16 09:49:47.025 -04:00 [Debug] Deleting trigger

**Desktop (please complete the following information):**
 - OS: Microsoft Windows x64 10.0.19041

**Ombi Version (please complete the following information):**
- Stable 3.0.4892
- Plex

**Comment by tidusjar** [comment] 2020-06-16 20:25
When attempting to authenticate with Plex, looks like incorrect credentials are being used. Please provide the correct credentials and then it will work.

> StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/friends/all/

**Comment by csc0ttbrown** [comment] 2020-06-16 20:30
Ombi does connect with my Plex server and my credentials are correct. This issue shouldn't be closed. If you want me to provide a screen recording of the problem I can, but I can't share it here because it would show off private information of users.

**Comment by tidusjar** [comment] 2020-06-16 21:50
Apologies about closing, sometimes I get a bit too trigger happy.

Basically what is incorrect is the Plex Auth token, we use that to get the friends list for the Plex server, but the Plex API is returning that we cannot authenticate due to an invalid token.

**Comment by csc0ttbrown** [comment] 2020-06-16 22:02
It's OK, thanks for reopening. I can verify that my Plex server is connected to Ombi by doing the following:

- Hit Settings
- Visit Media Server > Plex
- Hit "Test Connectivity"

When I do this, I see "Successfully connected to the Plex Server [My Plex Server Name Here]"

I should also mention that Ombi connects with my media files just fine as well. In other words, if I or a user searches for a film in my collection, Ombi shows that it is already in the library.

While I will gladly tweak settings, re-connect things, or what-have-you, the problem does not seem to be related to an incorrect Plex connection.

**Comment by twanariens** [comment] 2020-06-16 22:27
Tidusjar correct me if I am wrong but here goes my try:

The Plex "Test Connectivity" button only check whether Ombi can reach your Plex installation. That is where it gets it metadata for movies/tv shows/music from. But here comes the kicker, the Plex Authorization Token is used to connect to the Plex Configuration stored on the Plex servers itself. This configuration contains the users which you have shared your libraries with.

Since you are retrieving the metadata of movies, your connection to your Plex Server is fine. But since it doesn't import new users, there is probably a problem with retrieving data from the Plex servers. Can you check your Plex Authorization Token just to be sure there is nothing wrong there.

**Comment by csc0ttbrown** [comment] 2020-06-16 23:24
So, I am discovering that there are two types of authorization tokens: temporary and permanent. It could be that I only got a temporary token? Honestly, I don't remember even putting a token in there, I feel like that was something Ombi took care of when I logged in with my Plex credentials? I guess what I'm asking is how can I make sure the token is correct and/or get a new permanent token?

**Comment by csc0ttbrown** [comment] 2020-06-19 02:29
I don't want to be a pain but is there any assistance I can get with this? I just need explicit instructions on how to get a permanent token.

**Comment by tidusjar** [comment] 2020-06-19 08:33
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄


I am not sure if there are two types of tokens, if that is the case it's the first I have heard of it.
What you could do to aid the investigation is the following:
Call the following:
GET https://plex.tv/pms/friends/all`
With the header `X-Plex-Token:YourTokenFromTheSettings`

You can use something like cURL or Postman to do this.

**Comment by csc0ttbrown** [comment] 2020-06-19 12:52
It's totally OK, I understand. I will be donating to Ombi to help out!

The information I found related to two types of tokens is from here: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

I used Postman to run your request. However, there appeared to be an error in your URL. This is how I entered everything:

GET: https://plex.tv/pms/friends/all
HEADER KEY: X-Plex-Token
HEADER VALUE: <My Token>

If that all looks right, this is what returns:

`<?xml version="1.0" encoding="UTF-8"?>
<errors>
    <error>Invalid authentication token.</error>
</errors>`

Like I said earlier, Ombi was working just fine for a while and I never changed the token (I don't even remember putting in the token, but I must have?). The best possible explanation I have is that the token I put in was temporary and has now expired, unless you have another idea.

**Comment by tidusjar** [comment] 2020-06-19 13:09
OK, looking at that link, I can confirm we are 100% pulling the proper token: https://forums.plex.tv/t/how-to-request-a-x-plex-token-token-for-your-app/84551

But from our API response, it seems that the token is incorrect.

So when you type in the Plex username and password in on the Plex settings, It does the following to  get the token: https://forums.plex.tv/t/how-to-request-a-x-plex-token-token-for-your-app/84551

Can you do that manually and then recall the `https://plex.tv/pms/friends/all` with the new token?

**Comment by csc0ttbrown** [comment] 2020-06-19 14:11
OK, so that worked. I re-entered my UN and PW and the Plex token on the Settings page changed. Then when I did the GET process above, the code returned features all of my users, even the ones missing from Ombi. So this new token appears to work while the old token did not.

HOWEVER, when I visit Settings > Configuration > User Importer and then hit the "Run Importer" button, nothing happens. When I then go BACK to the Plex settings, the Token is different!

Somehow, hitting the "Run Importer" button is altering my Plex token. That appears to be the root of this issue.

**Comment by csc0ttbrown** [comment] 2020-06-19 14:16
WAIT, nevermind. I realize what happened here. The settings do not save automatically when you log in. So the new token appears after I enter my credentials, but none of the information gets saved. You need to enter in your credentials, see everything load properly, and then hit the Submit button at the lower left corner. That saves everything. That was my confusion.

So this is now fixed. However, it doesn't really explain why the token stopped working, but we can address that should it happen again. Thank you for all your help!

**Comment by tidusjar** [comment] 2020-06-19 14:55
Yeah, I do not understand why you had a stale token, I know this has happened previous when someone goes into their Plex Settings (On plex) and removed the Ombi Device from their list of devices.

But glad you are now up and running! Hope you are also looking forward to V4!

**Closed by tidusjar** 2020-06-19 14:55 UTC

**Comment by gsuave** [comment] 2023-02-22 17:06
token was the issue thanks
