### ISSUE TITLE
Error in Radarr scheduled job 

### ISSUE THREAD

**Issue by CBers** [tidusjar/Ombi#1211] opened 2017-03-02 08:42 UTC
#### Ombi Version:

Latest dev

#### Update Branch:

development

#### Media Sever:

Emby

#### Operating System:

Windows 7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/03/02 01:18:20.845 Ombi.Services.Jobs.RadarrCacher Error: Failed caching queued items from Radarr Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Models.Radarr.RadarrMovieResponse]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'page', line 2, position 9.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.RadarrApi.GetMovies(String apiKey, Uri baseUrl) in C:\projects\requestplex\Ombi.Api\RadarrApi.cs:line 166
   at Ombi.Services.Jobs.RadarrCacher.Queued() in C:\projects\requestplex\Ombi.Services\Jobs\RadarrCacher.cs:line 60
2017/03/02 05:21:20.706 Ombi.Services.Jobs.RadarrCacher Error: Failed caching queued items from Radarr Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Models.Radarr.RadarrMovieResponse]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'page', line 2, position 9.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.RadarrApi.GetMovies(String apiKey, Uri baseUrl) in C:\projects\requestplex\Ombi.Api\RadarrApi.cs:line 166
   at Ombi.Services.Jobs.RadarrCacher.Queued() in C:\projects\requestplex\Ombi.Services\Jobs\RadarrCacher.cs:line 60
2017/03/02 08:39:12.401 Ombi.Services.Jobs.EmbyAvailabilityChecker Debug: There are no requests to check. 

```

#### Problem Description:

Errors in Ombi logs 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment] 2017-03-02 08:51
duplicate of #1195 Can you look at that latest comment on that issue and if you have a minute can you try it?

**Closed by tidusjar** 2017-03-02 08:51 UTC
