### ISSUE TITLE
Requesting By Season Downloads Entire Show

### ISSUE THREAD

**Issue by keithwoelke** [tidusjar/Ombi#1422] opened 2017-06-06 00:47 UTC
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.5.5.3634

#### Operating System:

Ubuntu Zesty

#### Mono Version (only if you're not on Windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

{ "addOptions": { "ignoreEpisodesWithFiles": true, "ignoreEpisodesWithoutFiles": false, "searchForMissingEpisodes": true }, "title": "Bloodline", "seasons": [ { "seasonNumber": 1, "monitored": true, "statistics": null }, { "seasonNumber": 2, "monitored": false, "statistics": null }, { "seasonNumber": 3, "monitored": false, "statistics": null } ], "rootFolderPath": "/media/Storage/Videos/Common/TV Shows/", "qualityProfileId": 1, "seasonFolder": true, "monitored": true, "tvdbId": 287314, "tvRageId": 0, "cleanTitle": null, "imdbId": null, "titleSlug": "Bloodline", "id": 0, "images": [] }	Ombi.Api.SonarrApi	Debug	6/5/2017 5:39:41 PM
Sonarr API Options:	Ombi.Api.SonarrApi	Debug	6/5/2017 5:39:41 PM
```

#### Problem Description:

When using any of the season options (last, first, select seasons, etc), all seasons end up getting monitored. More specifically, the season is unmonitored, but every episode within the season remains monitored. So if I request the first season of a show (as in the posted log), Season 1 and all of its episodes are marked as monitored. However, seasons 2 and 3 will remain unmonitored at the season level, but every individual episode will be marked as monitored.

#### Reproduction Steps:

Add a show by season (first, last, or specific seasons). I added a show not already in Sonarr. I'm not sure if this matters.

**Comment by keithwoelke** [comment] 2017-06-06 01:21
This also seemed to work correctly when I used a separate user to request and then approved it with my admin user. It only seemed to have a problem when it auto-approved.

**Comment by Fiala06** [comment] 2017-06-20 17:24
I have the same issue.

The show I added wasn't in Sonarr. It did set the monitored show for S01 as I requested properly, but it downloaded all 5 seasons. Looking at the Ombi request page, it also stats correctly I only wanted S01.

I'm set to auto approve also and only have my 1 admin account. Windows 10 x64.

**Comment by weirdcrap** [comment] 2017-06-22 10:36
I believe this is a duplicate of this issue: https://github.com/tidusjar/Ombi/issues/1382

It is a problem specific to Sonarr, not Ombi. Hopefully the next public release of Sonarr contains the fix (it was committed about a month ago).

**Closed** 2017-06-22 11:30 UTC
