### ISSUE TITLE
Newsletter Formatting Issue - Overflow

### ISSUE THREAD

**Issue by galacticat** [tidusjar/Ombi#2246] opened 2018-05-11 13:43 UTC
#### Ombi build Version:

V 3.0.3299

#### Update Branch:

develop

#### Media Sever:

Plex

#### Media Server Version:

N/A
#### Operating System:

Ubuntu 16.04 w/ Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```



```

#### Problem Description:

Formatting issue in the newsletter. 2 of the entries overflowed to the right of the page
https://imgur.com/a/CM4KfYe
#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment] 2018-05-11 18:16
@anojht can you take a look at this one?

**Comment by anojht** [comment] 2018-05-11 19:40
@galacticat Is that gmail on desktop?

**Comment by galacticat** [comment] 2018-05-11 19:57
Yes, looked at it in the old Gmail view and the new Inbox view in Chrome. The original screenshots were taken docked to the left of a 21" monitor. Mobile seems to be fine because it is displaying only 1 item per row.

Full Screen in Inbox:
https://imgur.com/a/3EtjD6X

**Comment by anojht** [comment] 2018-05-11 21:44
hmm I am not able to reproduce this in my gmail, can you go to the newsletter settings and click the test button and let me know if the problem occurs with the test?

**Comment by galacticat** [comment] 2018-05-11 21:48
Does not occur in the Test. There are a lot fewer it's in the test though. I think I remember reading it's limited for the test.

**Comment by anojht** [comment] 2018-05-11 21:51
Thanks, are any of the same content from the buggy newsletter in the test? Just trying to figure out if overflow is being caused by TV cards with lots of new episodes added since the cards would need to be stretched. 

But the movies one is really throwing me off....

**Comment by galacticat** [comment] 2018-05-11 21:58
Red Sparrow was the one that over flowed before, doesn't in the test. 

https://imgur.com/a/ja7vWwi

**Comment by galacticat** [comment] 2018-05-12 01:01
Unfortunately put inside an HTML file it doesn't have any actual image data :-(. But I hope it helps with this.

https://pastebin.com/K66x2TGf

**Comment by anojht** [comment] 2018-05-12 02:13
Thanks man that helped a lot! I pushed a fix for it in develop if you see this problem again just reopen this issue 😄

**Closed by anojht** 2018-05-12 02:13 UTC
Labels: bug / issue
