### ISSUE TITLE
Unable to edit/delete/add local users

### ISSUE THREAD

**Issue by ronso21** [tidusjar/Ombi#2862] opened 2019-03-03 15:09 UTC
**Describe the bug**
Within the User Management section existing users cannot be updated (change password, email address).  Existing users cannot be deleted.  New users cannot be added.

When editing a user, deleting a user,or adding a user, the update button, the delete button, or the create button does nothing and the page just sits until you press the back button.  Pressing the back button loses the changes you were applying to the user account.

**To Reproduce**
Add, edit, or delete a local user account

**Expected behavior**
I expect the changes to be saved and appropriate

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
[log-20190303.txt](https://github.com/tidusjar/Ombi/files/2923249/log-20190303.txt)

**Desktop (please complete the following information):**
 - OS: Win10 v.1809 build 17763.316

**Ombi Version (please complete the following information):**
 - Version 3.0.4256 master fork
- Media Server Plex

**Additional context**
N/A

**Comment by tidusjar** [comment] 2019-03-03 22:09
Duplicate of#2750

**Closed by tidusjar** 2019-03-03 22:09 UTC
