### ISSUE TITLE
No movie ....

### ISSUE THREAD

**Issue by grego31430** [tidusjar/Ombi#2639] opened 2018-11-11 17:39 UTC
#### Ombi build Version:

V 3.0.3966 

#### Update Branch:

Beta

#### Media Sever:

Emby

#### Operating System:

Windows; Debian

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-11-11 13:44:39.382 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.TryExtractParameter(Expression expression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AnyAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Core.Engine.MovieSearchEngine.CheckForSubscription(SearchMovieViewModel viewModel)
   at Ombi.Core.Engine.MovieSearchEngine.ProcessSingleMovie(SearchMovieViewModel viewMovie, Boolean lookupExtraInfo) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 170
   at Ombi.Core.Engine.MovieSearchEngine.ProcessSingleMovie(MovieSearchResult movie) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 195
   at Ombi.Core.Engine.MovieSearchEngine.TransformMovieResultsToResponse(IEnumerable`1 movies) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 147
   at Ombi.Core.Engine.MovieSearchEngine.PopularMovies() in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 93
   at Ombi.Controllers.SearchController.Popular() in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 87
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

```

#### Problem Description:

No movie displayed, and when I search the error in the log popup

#### Reproduction Steps:

install new update by removing the old, and open

**Comment by tidusjar** [comment] 2018-11-11 18:36
Your going to have to be a bit more descriptive of what the issue is here...

**Comment by grego31430** [comment] 2018-11-11 19:31
When I launch Ombi, on windows or Debian, the Tab Movies, is empty, and in the consol I have the error.
if I tried to search a movies, the error re-show in the consol..

Sorry for my bad english :/

**Comment by grego31430** [comment] 2018-11-11 22:56
Yes 3 errors :
ERROR TypeError: "this.remaining is null"
	daysUntilNextRequest http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:23021
	calculateTime http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:22831
	n http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:22536
	__tryOrUnsub http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:2919
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:2061
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:1101
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1303:23340
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1310:83770
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	notifyNext http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1070:17565
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1070:14033
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	l http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:977:1630
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:7674
	onInvokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:186:1960
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:7587
	runTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:2846
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:8792
	v http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1474:432
	b http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1474:749
core.js:1624
$t
core.js:1624
Kt</t.prototype.handleError
core.js:1670
next
core.js:4252:109
mn</e.prototype.subscribe/i<
core.js:3488:34
p</e.prototype.__tryOrUnsub
Subscriber.js:195
p</e.prototype.next
Subscriber.js:133
c</e.prototype._next
Subscriber.js:77
c</e.prototype.next
Subscriber.js:54
p</e.prototype.next
Subject.js:47
mn</e.prototype.emit
core.js:3480:52
onHandleError/<
core.js:3779:48
s</t.prototype.invoke
zone.js:388
i</e.prototype.run
zone.js:138
yn</t.prototype.runOutsideAngular
core.js:3716
onHandleError
core.js:3779
s</t.prototype.handleError
zone.js:392
i</e.prototype.runTask
zone.js:191
u</e.invokeTask
zone.js:496
e/this.invoke
zone.js:485
s/n.args[0]
zone.js:2054
ERROR TypeError: "this.remaining is null"
	daysUntilNextRequest http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:23021
	calculateTime http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:22831
	n http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:22536
	__tryOrUnsub http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:2919
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:2061
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:1101
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1303:23340
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1310:83770
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	notifyNext http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1070:17565
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1070:14033
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	l http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:977:1630
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:7674
	onInvokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:186:1960
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:7587
	runTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:2846
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:8792
	v http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1474:432
	b http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1474:749
core.js:1624
ERROR TypeError: "this.remaining is null"
	daysUntilNextRequest http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:23021
	calculateTime http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:22831
	n http://localhost:5000/dist/10.0a08c011aa4bf58fdc2c.chunk.js:1:22536
	__tryOrUnsub http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:2919
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:2061
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:1101
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1303:23340
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1310:83770
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	notifyNext http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1070:17565
	_next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1070:14033
	next http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:867:784
	l http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:977:1630
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:7674
	onInvokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:186:1960
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:7587
	runTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:2846
	invokeTask http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1451:8792
	v http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1474:432
	b http://localhost:5000/dist/app.js?v=MyNiXJa2aVljQ-0MonNbAceAc-EB92LZF405YQ3pQ4M:1474:749
core.js:1624
ERROR 
{…}
​
error: Object { error: "Object reference not set to an instance of an object." }
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit()
 }
​
message: "Http failure response for http://localhost:5000/api/v1/search/Movie/Popular: 500 Internal Server Error"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 500
​
statusText: "Internal Server Error"
​
url: "http://localhost:5000/api/v1/search/Movie/Popular"
​
<prototype>: Object { constructor: e()
 }
core.js:1624

**Comment by grego31430** [comment] 2018-11-12 19:40
a little update, I have test with an old version (3.0.3919) and do exactly the same ...
they also don't show me the update :/

**Comment by tidusjar** [comment] 2018-11-12 20:45
Ok that error definitely helps.

**Comment by grego31430** [comment] 2018-11-12 20:50
you want the log of that version ?

**Comment by tidusjar** [comment] 2018-11-13 14:42
Fixed in develop

**Closed by tidusjar** 2018-11-13 14:42 UTC
