### ISSUE TITLE
Issue #2246 again - Newsletter formatting overflowing entries.

### ISSUE THREAD

**Issue by galacticat** [tidusjar/Ombi#2322] opened 2018-06-11 12:26 UTC
#### Ombi build Version:

V 3.0.3346

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Docker on Ubuntu 16.0.4

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Email Source Code:
https://pastebin.com/17rrezdq

```

#### Problem Description:

Several entries in the newsletter are overflowing the grid.

#### Reproduction Steps:

Screenshots:
https://imgur.com/a/aEhdSS0

**Comment by tidusjar** [comment] 2018-06-11 13:51
Emails client?

**Comment by galacticat** [comment] 2018-06-11 14:00
Gmail in Chrome

**Comment by tidusjar** [comment] 2018-06-13 20:30
@anojht Can you take a look at this?

**Comment by galacticat** [comment] 2018-06-13 23:39
https://pastebin.com/17rrezdq

**Comment by TheRealDirtyMike** [comment] 2018-06-15 14:48
I am seeing something similar when viewing the newsletter via the Android Gmail app. I DO NOT however see this behavior on the emails when viewed in Chrome on either the phone or computer.  Not sure if this issue is related to galacticat's issue but I figured this would be the best place to report it. Also since this only happens when using the GMAIL app, not sure if this is even related to Ombi config or code. 

**Ombi build Version**:
V 3.0.3383

**Update Branch**:
master

**Media Sever**:
Plex

**Media Server Version**:
N/A

**Operating System**:
Windows 10.0.17134

**Problem Description**:
Entries in the email seem to overlap with descriptions and other text. Only appears when viewing in the Gmail phone app. Android. 

**Screenshots**:
https://imgur.com/RPRy4EO
https://imgur.com/Q0KJq4w
https://imgur.com/y1shmoc

**Comment by galacticat** [comment] 2018-06-15 15:03
Saw it again this week in Gmail/Inbox on Chrome
https://imgur.com/a/k1wRdiM

This weeks newsletter source:
https://pastebin.com/KJ9kFxiA

I use the Inbox app on my Android phone, and if I go to my Sent box there and look at the emails it is all in one column with nothing overlapping. However; if I click the link at the end to "View Full Email" it shows up as it does in my browser.
https://imgur.com/a/j88RKda

**Comment by galacticat** [comment] 2018-06-22 13:51
More data points for troubleshooting hopefully.

https://pastebin.com/Z3xUpMeV

https://imgur.com/a/nMtklTc

**Comment by anojht** [comment] 2018-06-24 08:34
Thanks guys this maybe isolated to inbox/gmail something might have changed CSS compatibility wise, I am still working on fallback styling and ensuring best support across all these mail clients.

**Comment by tidusjar** [comment] 2018-06-24 13:02
That's for the help with this @anojht !!

**Comment by galacticat** [comment] 2018-06-29 19:42
The latest docker instance I am using is pointing at the master branch. Any idea where I can configure it to point to dev?

**Comment by anojht** [comment] 2018-06-29 19:45
AFAIK you can't switch branches like that with docker. However there is a container for dev branch: [ombi-preview](https://hub.docker.com/r/lsiodev/ombi-preview/)

**Comment by galacticat** [comment] 2018-06-29 19:51
Switched over to that image. I'll let you know next Friday lol

**Comment by tidusjar** [comment] 2018-06-29 20:04
You could manually trigger it?

**Comment by galacticat** [comment] 2018-06-29 21:24
For sending reaaon, I have never been able to reproduce this issue using the manual trigger. Possibly not enough comtemt to cause it

**Comment by galacticat** [comment] 2018-07-06 12:22
Still messing up this morning. I am running 3.0.3450 development branch

Screenshots:
https://imgur.com/a/If1j10W

Source:
https://pastebin.com/CHkyyGE0

**Comment by elit3ge** [comment] 2018-07-06 23:16
I got this morning on 3.0.3421

Gmail in Google Chrome

https://imgur.com/a/sjQZ0or

**Comment by anojht** [comment] 2018-07-09 18:02
Thanks for the data guys it has been really helpful. I spent last night debugging this extensively, I found exactly what's the cause of this. Rewriting a small part of it now, thanks for your patience! 😄

**Comment by anojht** [comment] 2018-07-09 18:23
Fix is in dev branch and being built, if someone wants to update and test the fix, there is a trigger now button in the newsletter settings page. It will grab the content added since last newsletter and send one.

**Comment by TheRealDirtyMike** [comment] 2018-07-09 18:41
I will be able to update and text in a few hours. Will let you know if it fixes formatting. 

Thanks for all the hard work!

**Comment by TheRealDirtyMike** [comment] 2018-07-10 01:19
UPDATE: 

I just updated to the latest Dev build 3.0.3473 and I am still seeing the same formatting issues when viewing in the GMAIL Android App. This isn't a HUGE issue for me as most of my users just delete the email anyway... and so far nobody has really complained about it..

HOWEVER, I do think this is related more towards how the content is displayed within the gmail app as each entry seems to be overlapping when viewing in a portrait orientation but I do not get overlap when viewing landscape. Like I said before, I have not had any issues with how the content is displayed while using gmail via Chrome on a computer so I do not believe my issues is related to Galacticat's.

Screenshots for reference
Android App
--------------
https://imgur.com/cHD49X3
https://imgur.com/qSeBZs9
https://imgur.com/dRElVaq

Chrome
---------
https://imgur.com/ikoDRGj
https://imgur.com/A4Umv2F

**Comment by anojht** [comment] 2018-07-10 01:22
Thanks @TheRealDirtyMike! yeah the app overlay is a known issue that I need to add some fallback CSS for. Just wanted to make sure the overflowed content was fixed first because that was definitely a backend bug.
I noticed in the chrome snippets everything seems ok, is TV fine too?

**Comment by galacticat** [comment] 2018-07-10 01:30
Looks like it's fixed to me. I triggered it with the new button and everything looks good.

**Comment by anojht** [comment] 2018-07-10 01:50
I will continue to add fallback styling to support more clients. Closing this issue now!

**Closed by anojht** 2018-07-10 01:50 UTC
Labels: bug / issue
