### ISSUE TITLE
Ombi Not displaying  on Home screen

### ISSUE THREAD

**Issue by capnhowyoudo** [tidusjar/Ombi#3281] opened 2019-11-23 19:01 UTC
**Describe the bug**

Ombi is not displaying on the home screen for Movies nor am i able to search under movies. 

TV shows are working for posters and search. 

**To Reproduce**
1. login to Ombi

**Expected behavior**
To have Ombi display posters and sections on home screen and be searchable

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Ombi Version (please complete the following information):**
 - Version  3.0.4892
- Media Server Plex

**Additional context**
![2019-11-23_12h50_44](https://user-images.githubusercontent.com/40323628/69483789-55717600-0df1-11ea-9d22-87a0e4313d03.png)
![2019-11-23_12h50_53](https://user-images.githubusercontent.com/40323628/69483790-573b3980-0df1-11ea-8bf3-0c90406f88d0.png)

**Comment by tidusjar** [comment] 2019-11-23 21:39
Duplicate of #3253

**Closed by tidusjar** 2019-11-23 21:39 UTC
