### ISSUE TITLE
Ombi v4.0.449 - Scrolling on mobile not working

### ISSUE THREAD

**Issue by dmike3** [tidusjar/Ombi#3722] opened 2020-08-14 20:54 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'to website on your mobile phone'
2. Click on 'try scrolling'
3. Scroll down to 'down to see the problem'

**Expected behavior**
It should scroll down over movies and TV shows. Instead, it gets stuck trying to zoom into the picture.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version v4.0.449
- Media Server Plex

**Additional context**

**Comment by bagobones** [comment] 2020-08-16 04:04
Seeing similar issues on iOS on iPhones 7, 8..

**Comment by PotatoQuality** [comment] 2020-08-16 09:17
Please full-in the issue template and not just part of it.

**Comment by MokiTa** [comment] 2020-08-20 22:25
The problem still exists on Ombi v4.0.451.
iOS 13.6. iPhone X
Safari
Ubuntu 16.04.6 LTS x64
Mono 5.8.0.127

**Comment by tidusjar** [comment] 2020-08-27 21:18
Duplicate of #3660

**Closed by tidusjar** 2020-08-27 21:18 UTC
