### ISSUE TITLE
v4 - Always an Update

### ISSUE THREAD

**Issue by MikeFalcor** [tidusjar/Ombi#3683] opened 2020-07-24 22:45 UTC
**Describe the bug**
In settings, (New Update Available) is ALWAYS present even though I am running the latest version.

**To Reproduce**
1. Go to Settings

**Expected behavior**
If you're running the latest version, it should NOT show (New Update Available) next to the version.

**Screenshots**
![Ombi Update Avail](https://user-images.githubusercontent.com/11777545/88440978-8eb91600-cdc4-11ea-8be1-db892266f5b4.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 2004

**Ombi Version (please complete the following information):**
 - Version: 4.0.411
 - Media Server: Plex

**Additional context**
N/A

**Comment by bakerboy448** [comment] 2020-07-31 17:25
dupe of https://github.com/tidusjar/Ombi/issues/3569

**Comment by tidusjar** [comment] 2020-08-27 21:20
Duplicate of #3569

**Closed by tidusjar** 2020-08-27 21:20 UTC
