### ISSUE TITLE
layout glitch request page

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#619] opened 2016-10-27 23:43 UTC
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9.5
#### Operating System:

windows 10
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```
#### Reproduction Steps:

Its look like we have a little layout glitch with the last version 1.9.5
![image](https://cloud.githubusercontent.com/assets/2944704/19789428/e29e50f4-9caf-11e6-8d16-a750ff0bb829.png)

**Comment by tidusjar** [comment] 2016-10-28 08:13
I cannot seem to reproduce this. Is there any way you can clear your cache?

**Comment by csy7550** [comment] 2016-11-01 21:52
I see you closed this issue. How did you solve it? I've cleared cache and the issue is still the same..

**Comment by SuperPotatoMen** [comment] 2016-11-01 22:05
I didn't fix it, so i guess its a bug?

**Comment by csy7550** [comment] 2016-11-02 08:42
Looks the same as your screenshot on android/chrome after clearing cache so I would say bug :)

**Comment by tidusjar** [comment] 2016-11-22 14:23
I still cannot reproduce this issue.
I do not have an Android phone to try it on though... Works fine on my my iPhone

**Comment by csy7550** [comment] 2016-11-22 19:01
Installed another browser (opera) and the glitch is still the same.. how can I help?

**Comment by tidusjar** [comment] 2016-11-22 20:20
Is this happening on any PC browsers or is it just mobile?

**Comment by csy7550** [comment] 2016-11-22 21:12
Only mobile as far as I can tell, regular user of chrome, firefox and edge/ie on desktop and never had any issues with them..

**Comment by SuperPotatoMen** [comment] 2016-11-22 23:43
If i force desktop version in chrome on my mobile, it is just fine.

I have the same problem to on the report page. its look like the ---- lines can't be rendered at all.

**Comment by tidusjar** [comment] 2016-11-23 09:12
That's strange, the reports page has not changed since I released it...

**Comment by SuperPotatoMen** [comment] 2016-12-02 09:24
I will test the fix this day.

**Comment by SuperPotatoMen** [comment] 2016-12-04 22:25
Tested the reverted, still have the bug. See discussion on gitter

**Comment by SuperPotatoMen** [comment] 2016-12-13 18:01
moved up the time line to the 1.10.1 release

**Comment by SuperPotatoMen** [comment] 2016-12-20 01:19
@tidusjar it is solved over here :/ After a fresh installation and deleted database it is now fine :/

**Comment by SuperPotatoMen** [comment] 2016-12-20 01:19
@csy7550 can you delete your database file and do a fresh installation?

**Comment by csy7550** [comment] 2016-12-20 08:42
I'll try.. alot on my todo-list so haven't upgraded yet..

**Comment by SuperPotatoMen** [comment] 2016-12-21 11:01
okay, i wait on @csy7550 feedback if we can close this one.

**Closed** 2016-12-29 12:16 UTC
Labels: V2.x, Waiting on feedback
